data = {
    "logo_path": "",
    "sheet_title": "Dallas Tradeshow Collection",
    "date": "06/25/2024",
    "products": [
        {
            "name": "Twinning Sable (Large, Beige) Marble Candle Holder",
            "sku": "WC_DC57-10003",
            "category": "Home Decor",
            "description": "The candle holder features a sleek and contemporary design...",
            "features": ["Marble body", "Beige", "Cream finish"],
            "available_units": 400,
            "price": 32,
            "moq": 15,
            "image_url": "",
            "long_text": "The candle holder features a sleek and contemporary design...",
            "style": "Vintage, Modern, Traditional, Rustic, Bohemian",
            "finish": "Matte",
            "color": "Beige",
        },
        {
            "name": "Twinning Sable (Large, Beige) Marble Candle Holder",
            "sku": "WC_DC57-10003",
            "category": "Home Decor",
            "description": "The candle holder features a sleek and contemporary design...",
            "features": ["Marble body", "Beige", "Cream finish"],
            "available_units": 400,
            "price": 32,
            "moq": 15,
            "image_url": "",
            "long_text": "The candle holder features a sleek and contemporary design...",
            "style": "Vintage, Modern, Traditional, Rustic, Bohemian",
            "finish": "Matte",
            "color": "Beige",
        },
        {
            "name": "Twinning Sable (Large, Beige) Marble Candle Holder",
            "sku": "WC_DC57-10003",
            "category": "Home Decor",
            "description": "The candle holder features a sleek and contemporary design...",
            "features": ["Marble body", "Beige", "Cream finish"],
            "available_units": 400,
            "price": 32,
            "moq": 15,
            "image_url": "",
            "long_text": "The candle holder features a sleek and contemporary design...",
            "style": "Vintage, Modern, Traditional, Rustic, Bohemian",
            "finish": "Matte",
            "color": "Beige",
        },
        {
            "name": "Twinning Sable (Large, Beige) Marble Candle Holder",
            "sku": "WC_DC57-10003",
            "category": "Home Decor",
            "description": "The candle holder features a sleek and contemporary design...",
            "features": ["Marble body", "Beige", "Cream finish"],
            "available_units": 400,
            "price": 32,
            "moq": 15,
            "image_url": "",
            "long_text": "The candle holder features a sleek and contemporary design...",
            "style": "Vintage, Modern, Traditional, Rustic, Bohemian",
            "finish": "Matte",
            "color": "Beige",
        },
        {
            "name": "Twinning Sable (Large, Beige) Marble Candle Holder",
            "sku": "WC_DC57-10003",
            "category": "Home Decor",
            "description": "The candle holder features a sleek and contemporary design...",
            "features": ["Marble body", "Beige", "Cream finish"],
            "available_units": 400,
            "price": 32,
            "moq": 15,
            "image_url": "",
            "long_text": "The candle holder features a sleek and contemporary design...",
            "style": "Vintage, Modern, Traditional, Rustic, Bohemian",
            "finish": "Matte",
            "color": "Beige",
        },
    ],
    "footer_link": "www.ashleyfurniture.com",
    "footer_link_text": "www.ashleyfurniture.com",
    "page_number": 1
}