data= {
            "system_id": "WC_00154",
            "buyer_name": "test",
            "doc_type": "Order",
            "buyer_contact_first_name": "Internal",
            "buyer_contact_last_name": "Mac",
            "document_written_for_name": "",
            "document_written_for_email": "",
            "document_written_for_phone": "",
            "document_written_for_department": "",
            "document_written_by_name": "",
            "document_written_by_email": "",
            "document_written_by_phone": "",
            "document_written_by_department": "",
            "buyer_contact_designation": "",
            "buyer_location": "test, US",
            "buyer_email": "jason@wizz.com",
            "buyer_phone": "7247452850",
            "shipping_method": "UPS",
            "shipping_terms": None,
            "payment_method": "Cash",
            "payment_terms": "Credit Card",
            "carrier_name": None,
            "freight_terms": "Third Party",
            "payment_status": "PENDING",
            "payment_status_label": "Payment Pending",
            "cart_total": "$ 120.00",
            "total": "$ 120.00",
            "total_amount_due": "$ 120.00",
            "total_payment_received": "$ 0.00",
            "all_payment_received_total": "$ 0.00",
            "all_payment_refunded_total": "$ 0.00",
            "excess_payment_received": "$ 0.00",
            "date": "01/24/2025",
            "date_scheduled": "",
            "date_issued": "",
            "vendor_po": None,
            "customer_po": None,
            "charges": [],
            "shipping_address": {
                "id": "b0633a86-ffa8-4220-8e4a-d9f2f4525b55",
                "first_name": "test",
                "last_name": "test",
                "phone": "+15555555",
                "email": "",
                "country": "United States of America",
                "street_address": "test",
                "address_line_2": "",
                "city": "test",
                "state": "",
                "pincode": "1234",
                "type": "shipping",
                "country_code": "AF",
                "8e9d4fb5-39fe-4b94-99b4-30407cd0db6b": "test",
                "attribute_values": [
                    {
                        "id": "8e9d4fb5-39fe-4b94-99b4-30407cd0db6b",
                        "name": "Company",
                        "type": "text",
                        "value": "test",
                        "priority": 4,
                        "required": True,
                        "is_display": True,
                        "options": [],
                        "updated_at": "2024-07-17T08:17:46.470505",
                        "created_at": "2024-07-05T14:16:01.015924",
                        "is_display_exclusion_type": [],
                        "required_exclusion_type": [],
                        "validations": {},
                        "is_label_display": False
                    }
                ]
            },
            "billing_address": {
                "id": "e9aed457-850a-4bfd-a165-b75e344232d2",
                "first_name": "test",
                "last_name": "test",
                "phone": "",
                "email": "",
                "country": "United States of America",
                "street_address": "test",
                "address_line_2": "",
                "city": "test",
                "state": "",
                "pincode": "1234",
                "type": "billing",
                "country_code": "AF",
                "8e9d4fb5-39fe-4b94-99b4-30407cd0db6b": "test",
                "attribute_values": [
                    {
                        "id": "8e9d4fb5-39fe-4b94-99b4-30407cd0db6b",
                        "name": "Company",
                        "type": "text",
                        "value": "test",
                        "priority": 4,
                        "required": True,
                        "is_display": True,
                        "options": [],
                        "updated_at": "2024-07-17T08:17:46.470505",
                        "created_at": "2024-07-05T14:16:01.015924",
                        "is_display_exclusion_type": [],
                        "required_exclusion_type": [],
                        "validations": {},
                        "is_label_display": False
                    }
                ]
            },
            "customer_notes": "Abdh",
            "user_notes": "",
            "products": [
                {
                    "ser_no": "1",
                    "image_url": "https://fileserver-g-p.sourcerer.tech/files/28c71490-ca87-4e39-86e3-ddc3ebb5ddb6?quality=20&transforms=%5B%5B%22resize%22%2C%7B%22width%22%3A100%2C%22height%22%3A100%2C%22background%22%3A%22white%22%2C%22fit%22%3A%22contain%22%7D%5D%5D",
                    "sku_id": "UNB 502",
                    "name": "Cloth Trifold Wallet - Assorted Hand Block Print, Fair Trade",
                    "qty": 12,
                    "price": "$ 10.00",
                    "raw_price": 10.0,
                    "base_price": "$ 10.00",
                    "raw_base_price": 10.0,
                    "currency": "$",
                    "amount": "$ 120.00",
                    "raw_amount": 120.0,
                    "hinges_values": "",
                    "offered_price": "$ 10.00",
                    "raw_offered_price": 10.0,
                    "discount": "",
                    "note": "",
                    "is_custom_product": False,
                    "product_attributes": [],
                    "applied_modifiers": {},
                    "inventory": {
                        "inventory_tracking_enabled": True,
                        "available_quantity": 397.0,
                        "reserved_quantity": 0.0,
                        "in_stock_quantity": 397.0,
                        "backorder_allowed": True,
                        "backorder_available_quantity": 200.0,
                        "backorder_reserved_quantity": 0.0,
                        "on_order_quantity": 0.0,
                        "on_order_date": None,
                        "total_available": 597.0,
                        "total_reserved": 0.0,
                        "inventory_status": "IN_STOCK",
                        "out_of_stock_threshold": 0.0,
                        "created_at": 1714991470.113516,
                        "created_at_milliseconds": 1714991470113,
                        "updated_at": 1719522388.627721,
                        "updated_at_milliseconds": 1719522388627,
                        "on_order_details": [
                            {
                                "quantity": 0,
                                "date": None,
                                "identifier": "on_order_0"
                            }
                        ],
                        "in_transit_details": [
                            {
                                "quantity": 0,
                                "date": None,
                                "identifier": "in_transit_0"
                            }
                        ],
                        "notes": ""
                    },
                    "group_number": 0,
                    "group_name": "Ungrouped",
                    "priority": 1,
                    "raw_group_total": 0,
                    "group_total": "$ 0"
                }
            ],
            "description_attr_id": "",
            "website": "www.wholesale.matrboomie.com",
            "header": "Matr Boomie",
            "section_header": "Product Details",
            "img_logo": "https://ultronapi-g-p.sourcerer.tech/artifact/v1/file/11aba9fa-597b-4aff-9090-fcb42fdb84c1",
            "tenant_address": "204 W Powell Lane\nUnit 1 , Austin Texas 78758, USA\nwholesale@matrboomie.com\nwholesale.matrboomie.com\n512.535.5228 Ext. 101",
            "sample_file": None,
            "attrs_to_show": [],
            "request_ship date2": "",
            "request_ship date": "2025-03-13",
            "order_rep": "NYNOW",
            "phone": "",
            "email": "",
            "all_document_data": {
                "id": "b009f329-3fbf-4824-97f4-12b8cdb8cfc1",
                "system_id": "WC_00154",
                "reference_id": None,
                "source": "sales_rep",
                "offline_system_id": "",
                "type": "order",
                "tenant_id": "ba25f694-45f6-4b64-b000-362650d3b1ab",
                "created_by": "b115ee24-483f-42a0-a54f-114734ceded6",
                "updated_by": "831b9633-8e50-4e03-a145-a3d943f04eb1",
                "owner": "b115ee24-483f-42a0-a54f-114734ceded6",
                "buyer_id": "b9d372e4-db1e-4f6a-a8a3-c996b5ed961f",
                "expired_at": None,
                "cart_id": "b56189ad-2453-4639-a71e-b25b90a706b0",
                "orignal_order_id": None,
                "date": None,
                "document_status": "draft",
                "total_value": 120.0,
                "payment_due_date": None,
                "payment_transaction_id": None,
                "payment_transaction_details": None,
                "payment_status": "PENDING",
                "attributes": {
                    "a7d79b6e-9480-4451-89ae-48155d91f018": "",
                    "15416135-da42-4f1f-8cf7-398152504e47": "Tradeshow/Event",
                    "acdd4bd1-5611-4f26-9442-88c5c0ae3f62": "NYNOW",
                    "6ba81ec7-03e2-4a59-a026-0ce220b63f57": "2025-03-13T04:00:00.000Z",
                    "4eb5383f-032f-4f51-bb83-93d4d84419ce": "2025 Summer",
                    "dbe56992-4799-477f-b35c-aae39d7c255d": "",
                    "0a316f8a-3383-408c-ac38-10a54ee8f6c3": "",
                    "c193ede5-2948-499e-a0f7-c06040155e5c": "",
                    "billing_address": {
                        "id": "e9aed457-850a-4bfd-a165-b75e344232d2",
                        "first_name": "test",
                        "last_name": "test",
                        "phone": "",
                        "email": "",
                        "country": "United States of America",
                        "street_address": "test",
                        "address_line_2": "",
                        "city": "test",
                        "state": "",
                        "pincode": "1234",
                        "type": "billing",
                        "country_code": "AF",
                        "8e9d4fb5-39fe-4b94-99b4-30407cd0db6b": "test",
                        "attribute_values": [
                            {
                                "id": "8e9d4fb5-39fe-4b94-99b4-30407cd0db6b",
                                "name": "Company",
                                "type": "text",
                                "value": "test",
                                "priority": 4,
                                "required": True,
                                "is_display": True,
                                "options": [],
                                "updated_at": "2024-07-17T08:17:46.470505",
                                "created_at": "2024-07-05T14:16:01.015924",
                                "is_display_exclusion_type": [],
                                "required_exclusion_type": [],
                                "validations": {},
                                "is_label_display": False
                            }
                        ]
                    },
                    "shipping_address": {
                        "id": "b0633a86-ffa8-4220-8e4a-d9f2f4525b55",
                        "first_name": "test",
                        "last_name": "test",
                        "phone": "+15555555",
                        "email": "",
                        "country": "United States of America",
                        "street_address": "test",
                        "address_line_2": "",
                        "city": "test",
                        "state": "",
                        "pincode": "1234",
                        "type": "shipping",
                        "country_code": "AF",
                        "8e9d4fb5-39fe-4b94-99b4-30407cd0db6b": "test",
                        "attribute_values": [
                            {
                                "id": "8e9d4fb5-39fe-4b94-99b4-30407cd0db6b",
                                "name": "Company",
                                "type": "text",
                                "value": "test",
                                "priority": 4,
                                "required": True,
                                "is_display": True,
                                "options": [],
                                "updated_at": "2024-07-17T08:17:46.470505",
                                "created_at": "2024-07-05T14:16:01.015924",
                                "is_display_exclusion_type": [],
                                "required_exclusion_type": [],
                                "validations": {},
                                "is_label_display": False
                            }
                        ]
                    },
                    "payment_method": "cash",
                    "payment_method_id": None,
                    "payment_terms": "credit_card",
                    "freight_terms": "Third_Party",
                    "notification_email_ids": [
                        "somesh.nagrani@gmail.com"
                    ],
                    "shipping_method": "ups",
                    "primary_contact": {
                        "first_name": "Internal",
                        "last_name": "Mac",
                        "phone": "7247452850",
                        "email": "jason@wizz.com",
                        "country_code": "+1",
                        "for_document_only": True,
                        "id": "3994fef0-7ea9-4011-bae7-d96e1ec4863e"
                    },
                    "shipping_terms": None,
                    "vendor_po": None,
                    "customer_po": None,
                    "carrier_name": None,
                    "carrier_service": None,
                    "date_scheduled": None,
                    "date_issued": None,
                    "auto_charges_calculation_enabled": False,
                    "customer_consent": False,
                    "signature": None,
                    "written_for": None,
                    "written_by": None,
                    "email_history": [],
                    "notes_settings": {
                        "customer_notes": {
                            "notes": "Abdh",
                            "share_this_note_with_buyer": True
                        },
                        "my_notes": {
                            "notes": "11111\n",
                            "share_this_note_with_buyer": False
                        }
                    },
                    "payment_method_v2": {}
                },
                "fulfillment_status": "UNFULFILLED",
                "fulfillment_details": None,
                "total_payment_received": None,
                "refund_details": None,
                "last_synced_with_source_at": None,
                "customer_consent": False,
                "signature": None,
                "entity_source": None,
                "is_sync": False,
                "last_sync_at": None,
                "last_sync_status": None,
                "last_sync_message": None,
                "reporting_attribute_1": None,
                "reporting_attribute_2": None,
                "reporting_attribute_3": None,
                "exported_date": None,
                "exported_method": None,
                "created_at": "08/06/2024",
                "updated_at": "2025-01-24T13:19:34.222664",
                "status": "published",
                "child": {},
                "charges": [],
                "total_amount_due": 120.0,
                "all_payment_received_total": 0,
                "all_payment_refunded_total": 0,
                "excess_payment_received": 0,
                "created_by_name": "",
                "created_by_email": "",
                "created_by_phone": "",
                "created_by_department": "",
                "updated_by_name": "Matr Boomie",
                "updated_by_email": "matrboomie@wizcommerce.com",
                "updated_by_phone": "9183929549",
                "updated_by_department": "",
                "written_by_name": "",
                "written_by_email": "",
                "written_by_phone": "",
                "written_by_department": "",
                "written_for_name": "",
                "written_for_email": "",
                "written_for_phone": "",
                "written_for_department": "",
                "sales_rep_name": "",
                "sales_rep_email": "",
                "sales_rep_phone": "",
                "sales_rep_department": "",
                "catalog_name": "Online Customer Price",
                "claim_form_added": False
            },
            "transactions": {
                "transactions": [],
                "invoices": [],
                "total_authorized_amount": 0
            },
            "buyer_details": {
                "id": "b9d372e4-db1e-4f6a-a8a3-c996b5ed961f",
                "name": "test",
                "reference_id": "gid://shopify/Customer/7137662107958",
                "type_of_customer": None,
                "sales_rep": "Team MB",
                "sales_rep_email": "wholesale@matrboomie.com",
                "sales_rep_phone": "",
                "sales_rep_department": "",
                "buyer_group": None,
                "location": "test, US",
                "contact_person_name": "-",
                "label": {
                    "background_color": "",
                    "text_color": "",
                    "text": ""
                },
                "primary_contact": {
                    "email": "",
                    "phone": "",
                    "country_code": ""
                },
                "payment_method": {},
                "wallet_balance": 0.0,
                "analytics": {
                    "today": {
                        "total_revenue": {
                            "value": "6,200",
                            "percentage": "100%",
                            "orders": 2,
                            "quotes": 5
                        },
                        "total_orders": {
                            "value": "2",
                            "biggest_order": "4,000"
                        },
                        "total_quotes": {
                            "value": "5",
                            "biggest_quote": "ABC",
                            "biggest_quote_value": "13,450"
                        },
                        "total_drafts": {
                            "value": "16",
                            "orders": 10,
                            "quotes": 6
                        }
                    },
                    "last_week": {},
                    "last_30_days": {},
                    "last_6_months": {},
                    "last_12_months": {},
                    "all_time": {}
                },
                "recent_orders": [
                    {
                        "date": "12 Aug 2023",
                        "type": "sent",
                        "id": 123456789,
                        "items": 12,
                        "price": "4,000",
                        "label": {
                            "background_color": "",
                            "text_color": "",
                            "text": ""
                        }
                    },
                    {
                        "date": "12 Aug 2023",
                        "type": "sent",
                        "id": 123456789,
                        "items": 12,
                        "price": "2,200"
                    }
                ]
            },
            "buyer_attributes": [
                {
                    "id": "e3fb0aba-532a-4e45-b364-e9516c92cd97",
                    "name": "Tags",
                    "type": "select",
                    "value": "Brick & Mortar,Fairtrade,Independent,Web Search",
                    "priority": 0,
                    "required": False,
                    "is_display": True,
                    "options": [
                        {
                            "label": "B2B",
                            "value": "b2b"
                        },
                        {
                            "label": "WizCommerce",
                            "value": "wizcommerce"
                        }
                    ],
                    "updated_at": "2024-07-02T10:11:41.700666",
                    "created_at": "2024-07-02T10:11:41.700666",
                    "is_display_exclusion_type": [],
                    "required_exclusion_type": [],
                    "validations": {},
                    "is_label_display": False
                },
                {
                    "id": "968b93e6-daf5-4a7e-8cd6-1e417f21515f",
                    "name": "Note",
                    "type": "text",
                    "value": "",
                    "priority": 1,
                    "required": False,
                    "is_display": True,
                    "options": [],
                    "updated_at": "2024-07-02T10:11:56.260903",
                    "created_at": "2024-07-02T10:11:56.260903",
                    "is_display_exclusion_type": [],
                    "required_exclusion_type": [],
                    "validations": {},
                    "is_label_display": False
                }
            ],
            "contact_attributes": {},
            "address_attributes": {
                "e9aed457-850a-4bfd-a165-b75e344232d2": [
                    {
                        "id": "8e9d4fb5-39fe-4b94-99b4-30407cd0db6b",
                        "name": "Company",
                        "type": "text",
                        "value": "test",
                        "priority": 4,
                        "required": True,
                        "is_display": True,
                        "options": [],
                        "updated_at": "2024-07-17T08:17:46.470505",
                        "created_at": "2024-07-05T14:16:01.015924",
                        "is_display_exclusion_type": [],
                        "required_exclusion_type": [],
                        "validations": {},
                        "is_label_display": False
                    }
                ],
                "b0633a86-ffa8-4220-8e4a-d9f2f4525b55": [
                    {
                        "id": "8e9d4fb5-39fe-4b94-99b4-30407cd0db6b",
                        "name": "Company",
                        "type": "text",
                        "value": "test",
                        "priority": 4,
                        "required": True,
                        "is_display": True,
                        "options": [],
                        "updated_at": "2024-07-17T08:17:46.470505",
                        "created_at": "2024-07-05T14:16:01.015924",
                        "is_display_exclusion_type": [],
                        "required_exclusion_type": [],
                        "validations": {},
                        "is_label_display": False
                    }
                ]
            },
            "signature": "",
            "document_status": "draft",
            "document_created_by_name": "",
            "document_created_by_email": "",
            "document_created_by_phone": "",
            "document_created_by_department": "",
            "document_updated_by_name": "Matr Boomie",
            "document_updated_by_email": "matrboomie@wizcommerce.com",
            "document_updated_by_phone": "9183929549",
            "document_updated_by_department": "",
            "document_sales_rep": "",
            "document_sales_rep_email": "",
            "document_sales_rep_phone": "",
            "document_sales_rep_department": "",
            "timezone": "America/New_York",
            "timezone_code": "EST",
            "po_number": ""
        }