data = {
            "system_id": "WC_00011",
            "buyer_name": "Wizcommerce Test",
            "doc_type": "Order",
            "buyer_contact_first_name": "John",
            "buyer_contact_last_name": "Mac",
            "document_written_for_name": "Art Studio Company",
            "document_written_for_email": "artstudio@wizcommerce.com",
            "document_written_for_phone": "9048922912",
            "document_written_for_department": "",
            "document_written_by_name": "Art Studio Company",
            "document_written_by_email": "artstudio@wizcommerce.com",
            "document_written_by_phone": "9048922912",
            "document_written_by_department": "",
            "buyer_contact_designation": "CEO",
            "buyer_location": "Bangor, USA",
            "buyer_email": "Johnmac@wizcommerce.com",
            "buyer_phone": "9199999999",
            "shipping_method": "",
            "shipping_terms": None,
            "payment_method": "",
            "payment_terms": "",
            "carrier_name": None,
            "freight_terms": "",
            "payment_status": "PENDING",
            "payment_status_label": "Payment Pending",
            "cart_total": "$ 200.85",
            "total": "$ 276.75",
            "total_amount_due": "$ 276.75",
            "total_payment_received": "$ 0.00",
            "all_payment_received_total": "$ 0.00",
            "all_payment_refunded_total": "$ 0.00",
            "excess_payment_received": "$ 0.00",
            "date": "01/24/2025",
            "date_scheduled": "",
            "date_issued": "",
            "vendor_po": None,
            "customer_po": None,
            "charges": [
                {
                    "charge_name": "Discount",
                    "charge_value": "- $ 24.10",
                    "percentage": "12.0 %"
                },
                {
                    "charge_name": "Shipping",
                    "charge_value": "$ 100.00",
                    "percentage": ""
                }
            ],
            "shipping_address": {
                "id": "b3ef825f-e1bb-4e08-967c-b8b5985a80d8",
                "first_name": "John",
                "last_name": "Mac",
                "country_code": "+1",
                "phone": "9048922912",
                "email": "Johnmac@wizcommerce.com",
                "city": "New York",
                "state": "New York",
                "country": "USA",
                "pincode": "10038",
                "street_address": "123 William St",
                "address_line_2": "New York County",
                "reference_id": "",
                "attribute_values": []
            },
            "billing_address": {
                "id": "a4aa16fb-22c1-4d51-b23e-549b4952cf0e",
                "first_name": "John",
                "last_name": "Mac",
                "country_code": "+1",
                "phone": "9048922912",
                "email": "Johnmac@wizcommerce.com",
                "city": "Bangor",
                "state": "MI",
                "country": "USA",
                "pincode": "48150",
                "street_address": "14th Street, Penobscot County",
                "address_line_2": "New York County",
                "reference_id": "",
                "attribute_values": []
            },
            "customer_notes": "Test Check",
            "user_notes": "Test Check",
            "products": [
                {
                    "ser_no": "1",
                    "image_url": "https://fileserver-g-p.sourcerer.tech/files/700b5b2a-f807-4cdd-a468-14d73a8c404d?quality=20&transforms=%5B%5B%22resize%22%2C%7B%22width%22%3A100%2C%22height%22%3A100%2C%22background%22%3A%22white%22%2C%22fit%22%3A%22contain%22%7D%5D%5D",
                    "sku_id": "10561",
                    "name": "8344 Giraffe YEL Saint Louis",
                    "qty": 1,
                    "price": "$ 6.50",
                    "raw_price": 6.5,
                    "base_price": "$ 6.50",
                    "raw_base_price": 6.5,
                    "currency": "$",
                    "amount": "$ 6.50",
                    "raw_amount": 6.5,
                    "hinges_values": "",
                    "offered_price": "$ 6.50",
                    "raw_offered_price": 6.5,
                    "discount": "",
                    "note": "",
                    "is_custom_product": False,
                    "product_attributes": [],
                    "applied_modifiers": {},
                    "inventory": {
                        "inventory_tracking_enabled": False,
                        "available_quantity": 0.0,
                        "reserved_quantity": 0.0,
                        "in_stock_quantity": 0.0,
                        "backorder_allowed": False,
                        "backorder_available_quantity": 0,
                        "backorder_reserved_quantity": 0.0,
                        "on_order_quantity": 0.0,
                        "on_order_date": None,
                        "total_available": 0.0,
                        "total_reserved": 0.0,
                        "inventory_status": "IN_STOCK",
                        "out_of_stock_threshold": 0.0,
                        "created_at": 1725365731.924224,
                        "created_at_milliseconds": 1725365731924,
                        "updated_at": 1725365731.924224,
                        "updated_at_milliseconds": 1725365731924,
                        "on_order_details": [
                            {
                                "quantity": 0.0,
                                "date": None,
                                "identifier": "on_order_0"
                            }
                        ],
                        "in_transit_details": [],
                        "notes": ""
                    },
                    "group_number": 0,
                    "group_name": "Ungrouped",
                    "priority": 1,
                    "raw_group_total": 0,
                    "group_total": "$ 0"
                },
                {
                    "ser_no": "2",
                    "image_url": "https://fileserver-g-p.sourcerer.tech/files/903dceff-1d5b-482f-ba8b-4abed06682fb?quality=20&transforms=%5B%5B%22resize%22%2C%7B%22width%22%3A100%2C%22height%22%3A100%2C%22background%22%3A%22white%22%2C%22fit%22%3A%22contain%22%7D%5D%5D",
                    "sku_id": "10256",
                    "name": "8290 Seahorse Gold St Barth",
                    "qty": 1,
                    "price": "$ 6.00",
                    "raw_price": 6.0,
                    "base_price": "$ 6.00",
                    "raw_base_price": 6.0,
                    "currency": "$",
                    "amount": "$ 6.00",
                    "raw_amount": 6.0,
                    "hinges_values": "",
                    "offered_price": "$ 6.00",
                    "raw_offered_price": 6.0,
                    "discount": "",
                    "note": "",
                    "is_custom_product": False,
                    "product_attributes": [],
                    "applied_modifiers": {},
                    "inventory": {
                        "inventory_tracking_enabled": False,
                        "available_quantity": 0.0,
                        "reserved_quantity": 0.0,
                        "in_stock_quantity": 0.0,
                        "backorder_allowed": False,
                        "backorder_available_quantity": 0,
                        "backorder_reserved_quantity": 0.0,
                        "on_order_quantity": 0.0,
                        "on_order_date": None,
                        "total_available": 0.0,
                        "total_reserved": 0.0,
                        "inventory_status": "IN_STOCK",
                        "out_of_stock_threshold": 0.0,
                        "created_at": 1725365731.924224,
                        "created_at_milliseconds": 1725365731924,
                        "updated_at": 1725365731.924224,
                        "updated_at_milliseconds": 1725365731924,
                        "on_order_details": [
                            {
                                "quantity": 0.0,
                                "date": None,
                                "identifier": "on_order_0"
                            }
                        ],
                        "in_transit_details": [],
                        "notes": ""
                    },
                    "group_number": 0,
                    "group_name": "Ungrouped",
                    "priority": 2,
                    "raw_group_total": 0,
                    "group_total": "$ 0"
                },
                {
                    "ser_no": "3",
                    "image_url": "https://fileserver-g-p.sourcerer.tech/files/a49a5e37-9069-4b66-a7c4-4acd71a4dd5f?quality=20&transforms=%5B%5B%22resize%22%2C%7B%22width%22%3A100%2C%22height%22%3A100%2C%22background%22%3A%22white%22%2C%22fit%22%3A%22contain%22%7D%5D%5D",
                    "sku_id": "19103",
                    "name": "4075 Elephants with Leaves Apr",
                    "qty": 1,
                    "price": "$ 7.50",
                    "raw_price": 7.5,
                    "base_price": "$ 7.50",
                    "raw_base_price": 7.5,
                    "currency": "$",
                    "amount": "$ 7.50",
                    "raw_amount": 7.5,
                    "hinges_values": "",
                    "offered_price": "$ 7.50",
                    "raw_offered_price": 7.5,
                    "discount": "",
                    "note": "",
                    "is_custom_product": False,
                    "product_attributes": [],
                    "applied_modifiers": {},
                    "inventory": {
                        "inventory_tracking_enabled": False,
                        "available_quantity": 0.0,
                        "reserved_quantity": 0.0,
                        "in_stock_quantity": 0.0,
                        "backorder_allowed": False,
                        "backorder_available_quantity": 0,
                        "backorder_reserved_quantity": 0.0,
                        "on_order_quantity": 0.0,
                        "on_order_date": None,
                        "total_available": 0.0,
                        "total_reserved": 0.0,
                        "inventory_status": "IN_STOCK",
                        "out_of_stock_threshold": 0.0,
                        "created_at": 1725365731.924224,
                        "created_at_milliseconds": 1725365731924,
                        "updated_at": 1725365731.924224,
                        "updated_at_milliseconds": 1725365731924,
                        "on_order_details": [
                            {
                                "quantity": 0.0,
                                "date": None,
                                "identifier": "on_order_0"
                            }
                        ],
                        "in_transit_details": [],
                        "notes": ""
                    },
                    "group_number": 0,
                    "group_name": "Ungrouped",
                    "priority": 3,
                    "raw_group_total": 0,
                    "group_total": "$ 0"
                },
                {
                    "ser_no": "4",
                    "image_url": "https://fileserver-g-p.sourcerer.tech/files/46853cb3-9f04-4098-9f64-5ef3c318942c?quality=20&transforms=%5B%5B%22resize%22%2C%7B%22width%22%3A100%2C%22height%22%3A100%2C%22background%22%3A%22white%22%2C%22fit%22%3A%22contain%22%7D%5D%5D",
                    "sku_id": "19111",
                    "name": "4198 Flamingos with Flowers",
                    "qty": 1,
                    "price": "$ 7.50",
                    "raw_price": 7.5,
                    "base_price": "$ 7.50",
                    "raw_base_price": 7.5,
                    "currency": "$",
                    "amount": "$ 7.50",
                    "raw_amount": 7.5,
                    "hinges_values": "",
                    "offered_price": "$ 7.50",
                    "raw_offered_price": 7.5,
                    "discount": "",
                    "note": "",
                    "is_custom_product": False,
                    "product_attributes": [],
                    "applied_modifiers": {},
                    "inventory": {
                        "inventory_tracking_enabled": False,
                        "available_quantity": 0.0,
                        "reserved_quantity": 0.0,
                        "in_stock_quantity": 0.0,
                        "backorder_allowed": False,
                        "backorder_available_quantity": 0,
                        "backorder_reserved_quantity": 0.0,
                        "on_order_quantity": 0.0,
                        "on_order_date": None,
                        "total_available": 0.0,
                        "total_reserved": 0.0,
                        "inventory_status": "IN_STOCK",
                        "out_of_stock_threshold": 0.0,
                        "created_at": 1725365731.924224,
                        "created_at_milliseconds": 1725365731924,
                        "updated_at": 1725365731.924224,
                        "updated_at_milliseconds": 1725365731924,
                        "on_order_details": [
                            {
                                "quantity": 0.0,
                                "date": None,
                                "identifier": "on_order_0"
                            }
                        ],
                        "in_transit_details": [],
                        "notes": ""
                    },
                    "group_number": 0,
                    "group_name": "Ungrouped",
                    "priority": 4,
                    "raw_group_total": 0,
                    "group_total": "$ 0"
                },
                {
                    "ser_no": "5",
                    "image_url": "https://fileserver-g-p.sourcerer.tech/files/f8da29f5-4a55-47cf-ab9c-5993377ac891?quality=20&transforms=%5B%5B%22resize%22%2C%7B%22width%22%3A100%2C%22height%22%3A100%2C%22background%22%3A%22white%22%2C%22fit%22%3A%22contain%22%7D%5D%5D",
                    "sku_id": "19306",
                    "name": "5522 RMNP Landmarks and Nature",
                    "qty": 1,
                    "price": "$ 7.50",
                    "raw_price": 7.5,
                    "base_price": "$ 7.50",
                    "raw_base_price": 7.5,
                    "currency": "$",
                    "amount": "$ 7.50",
                    "raw_amount": 7.5,
                    "hinges_values": "",
                    "offered_price": "$ 7.50",
                    "raw_offered_price": 7.5,
                    "discount": "",
                    "note": "",
                    "is_custom_product": False,
                    "product_attributes": [],
                    "applied_modifiers": {},
                    "inventory": {
                        "inventory_tracking_enabled": False,
                        "available_quantity": 0.0,
                        "reserved_quantity": 0.0,
                        "in_stock_quantity": 0.0,
                        "backorder_allowed": False,
                        "backorder_available_quantity": 0,
                        "backorder_reserved_quantity": 0.0,
                        "on_order_quantity": 0.0,
                        "on_order_date": None,
                        "total_available": 0.0,
                        "total_reserved": 0.0,
                        "inventory_status": "IN_STOCK",
                        "out_of_stock_threshold": 0.0,
                        "created_at": 1725365731.924224,
                        "created_at_milliseconds": 1725365731924,
                        "updated_at": 1725365731.924224,
                        "updated_at_milliseconds": 1725365731924,
                        "on_order_details": [
                            {
                                "quantity": 0.0,
                                "date": None,
                                "identifier": "on_order_0"
                            }
                        ],
                        "in_transit_details": [],
                        "notes": ""
                    },
                    "group_number": 0,
                    "group_name": "Ungrouped",
                    "priority": 5,
                    "raw_group_total": 0,
                    "group_total": "$ 0"
                },
                {
                    "ser_no": "6",
                    "image_url": "https://sourcerer.tech/assets/e79f8cf2-4639-4ed6-998f-6e5a393f510b",
                    "sku_id": "19313",
                    "name": "5591 YNP Postal Stamp Apron",
                    "qty": 1,
                    "price": "$ 7.50",
                    "raw_price": 7.5,
                    "base_price": "$ 7.50",
                    "raw_base_price": 7.5,
                    "currency": "$",
                    "amount": "$ 7.50",
                    "raw_amount": 7.5,
                    "hinges_values": "",
                    "offered_price": "$ 7.50",
                    "raw_offered_price": 7.5,
                    "discount": "",
                    "note": "",
                    "is_custom_product": False,
                    "product_attributes": [],
                    "applied_modifiers": {},
                    "inventory": {
                        "inventory_tracking_enabled": False,
                        "available_quantity": 0.0,
                        "reserved_quantity": 0.0,
                        "in_stock_quantity": 0.0,
                        "backorder_allowed": False,
                        "backorder_available_quantity": 0,
                        "backorder_reserved_quantity": 0.0,
                        "on_order_quantity": 0.0,
                        "on_order_date": None,
                        "total_available": 0.0,
                        "total_reserved": 0.0,
                        "inventory_status": "IN_STOCK",
                        "out_of_stock_threshold": 0.0,
                        "created_at": 1725365731.924224,
                        "created_at_milliseconds": 1725365731924,
                        "updated_at": 1725365731.924224,
                        "updated_at_milliseconds": 1725365731924,
                        "on_order_details": [
                            {
                                "quantity": 0.0,
                                "date": None,
                                "identifier": "on_order_0"
                            }
                        ],
                        "in_transit_details": [],
                        "notes": ""
                    },
                    "group_number": 0,
                    "group_name": "Ungrouped",
                    "priority": 6,
                    "raw_group_total": 0,
                    "group_total": "$ 0"
                },
                {
                    "ser_no": "7",
                    "image_url": "https://fileserver-g-p.sourcerer.tech/files/b11c36d3-f69e-42d8-84bb-c215bc9db670?quality=20&transforms=%5B%5B%22resize%22%2C%7B%22width%22%3A100%2C%22height%22%3A100%2C%22background%22%3A%22white%22%2C%22fit%22%3A%22contain%22%7D%5D%5D",
                    "sku_id": "19425",
                    "name": "6406 Lake Placid Moose Hcky Apr",
                    "qty": 1,
                    "price": "$ 7.50",
                    "raw_price": 7.5,
                    "base_price": "$ 7.50",
                    "raw_base_price": 7.5,
                    "currency": "$",
                    "amount": "$ 7.50",
                    "raw_amount": 7.5,
                    "hinges_values": "",
                    "offered_price": "$ 7.50",
                    "raw_offered_price": 7.5,
                    "discount": "",
                    "note": "",
                    "is_custom_product": False,
                    "product_attributes": [],
                    "applied_modifiers": {},
                    "inventory": {
                        "inventory_tracking_enabled": False,
                        "available_quantity": 0.0,
                        "reserved_quantity": 0.0,
                        "in_stock_quantity": 0.0,
                        "backorder_allowed": False,
                        "backorder_available_quantity": 0,
                        "backorder_reserved_quantity": 0.0,
                        "on_order_quantity": 0.0,
                        "on_order_date": None,
                        "total_available": 0.0,
                        "total_reserved": 0.0,
                        "inventory_status": "IN_STOCK",
                        "out_of_stock_threshold": 0.0,
                        "created_at": 1725365731.924224,
                        "created_at_milliseconds": 1725365731924,
                        "updated_at": 1725365731.924224,
                        "updated_at_milliseconds": 1725365731924,
                        "on_order_details": [
                            {
                                "quantity": 0.0,
                                "date": None,
                                "identifier": "on_order_0"
                            }
                        ],
                        "in_transit_details": [],
                        "notes": ""
                    },
                    "group_number": 0,
                    "group_name": "Ungrouped",
                    "priority": 7,
                    "raw_group_total": 0,
                    "group_total": "$ 0"
                },
                {
                    "ser_no": "8",
                    "image_url": "https://fileserver-g-p.sourcerer.tech/files/c78be594-4e2d-4cb6-9b65-ca8e24946b24?quality=20&transforms=%5B%5B%22resize%22%2C%7B%22width%22%3A100%2C%22height%22%3A100%2C%22background%22%3A%22white%22%2C%22fit%22%3A%22contain%22%7D%5D%5D",
                    "sku_id": "19451",
                    "name": "6642 Custer State Prk Bison Apr",
                    "qty": 1,
                    "price": "$ 7.50",
                    "raw_price": 7.5,
                    "base_price": "$ 7.50",
                    "raw_base_price": 7.5,
                    "currency": "$",
                    "amount": "$ 7.50",
                    "raw_amount": 7.5,
                    "hinges_values": "",
                    "offered_price": "$ 7.50",
                    "raw_offered_price": 7.5,
                    "discount": "",
                    "note": "",
                    "is_custom_product": False,
                    "product_attributes": [],
                    "applied_modifiers": {},
                    "inventory": {
                        "inventory_tracking_enabled": False,
                        "available_quantity": 0.0,
                        "reserved_quantity": 0.0,
                        "in_stock_quantity": 0.0,
                        "backorder_allowed": False,
                        "backorder_available_quantity": 0,
                        "backorder_reserved_quantity": 0.0,
                        "on_order_quantity": 0.0,
                        "on_order_date": None,
                        "total_available": 0.0,
                        "total_reserved": 0.0,
                        "inventory_status": "IN_STOCK",
                        "out_of_stock_threshold": 0.0,
                        "created_at": 1725365731.924224,
                        "created_at_milliseconds": 1725365731924,
                        "updated_at": 1725365731.924224,
                        "updated_at_milliseconds": 1725365731924,
                        "on_order_details": [
                            {
                                "quantity": 0.0,
                                "date": None,
                                "identifier": "on_order_0"
                            }
                        ],
                        "in_transit_details": [],
                        "notes": ""
                    },
                    "group_number": 0,
                    "group_name": "Ungrouped",
                    "priority": 8,
                    "raw_group_total": 0,
                    "group_total": "$ 0"
                },
                {
                    "ser_no": "9",
                    "image_url": "https://fileserver-g-p.sourcerer.tech/files/e151c6f6-c228-47b2-8a6c-733d6314980f?quality=20&transforms=%5B%5B%22resize%22%2C%7B%22width%22%3A100%2C%22height%22%3A100%2C%22background%22%3A%22white%22%2C%22fit%22%3A%22contain%22%7D%5D%5D",
                    "sku_id": "19464",
                    "name": "6796 Colonial Williamsburg Aprn",
                    "qty": 1,
                    "price": "$ 7.50",
                    "raw_price": 7.5,
                    "base_price": "$ 7.50",
                    "raw_base_price": 7.5,
                    "currency": "$",
                    "amount": "$ 7.50",
                    "raw_amount": 7.5,
                    "hinges_values": "",
                    "offered_price": "$ 7.50",
                    "raw_offered_price": 7.5,
                    "discount": "",
                    "note": "",
                    "is_custom_product": False,
                    "product_attributes": [],
                    "applied_modifiers": {},
                    "inventory": {
                        "inventory_tracking_enabled": False,
                        "available_quantity": 0.0,
                        "reserved_quantity": 0.0,
                        "in_stock_quantity": 0.0,
                        "backorder_allowed": False,
                        "backorder_available_quantity": 0,
                        "backorder_reserved_quantity": 0.0,
                        "on_order_quantity": 0.0,
                        "on_order_date": None,
                        "total_available": 0.0,
                        "total_reserved": 0.0,
                        "inventory_status": "IN_STOCK",
                        "out_of_stock_threshold": 0.0,
                        "created_at": 1725365731.924224,
                        "created_at_milliseconds": 1725365731924,
                        "updated_at": 1725365731.924224,
                        "updated_at_milliseconds": 1725365731924,
                        "on_order_details": [
                            {
                                "quantity": 0.0,
                                "date": None,
                                "identifier": "on_order_0"
                            }
                        ],
                        "in_transit_details": [],
                        "notes": ""
                    },
                    "group_number": 0,
                    "group_name": "Ungrouped",
                    "priority": 9,
                    "raw_group_total": 0,
                    "group_total": "$ 0"
                },
                {
                    "ser_no": "10",
                    "image_url": "https://fileserver-g-p.sourcerer.tech/files/e690eb35-396e-4e83-bd65-c1777ac55fce?quality=20&transforms=%5B%5B%22resize%22%2C%7B%22width%22%3A100%2C%22height%22%3A100%2C%22background%22%3A%22white%22%2C%22fit%22%3A%22contain%22%7D%5D%5D",
                    "sku_id": "19471",
                    "name": "6871 Steamboat Skis & Poles Ap",
                    "qty": 1,
                    "price": "$ 7.50",
                    "raw_price": 7.5,
                    "base_price": "$ 7.50",
                    "raw_base_price": 7.5,
                    "currency": "$",
                    "amount": "$ 7.50",
                    "raw_amount": 7.5,
                    "hinges_values": "",
                    "offered_price": "$ 7.50",
                    "raw_offered_price": 7.5,
                    "discount": "",
                    "note": "",
                    "is_custom_product": False,
                    "product_attributes": [],
                    "applied_modifiers": {},
                    "inventory": {
                        "inventory_tracking_enabled": False,
                        "available_quantity": 0.0,
                        "reserved_quantity": 0.0,
                        "in_stock_quantity": 0.0,
                        "backorder_allowed": False,
                        "backorder_available_quantity": 0,
                        "backorder_reserved_quantity": 0.0,
                        "on_order_quantity": 0.0,
                        "on_order_date": None,
                        "total_available": 0.0,
                        "total_reserved": 0.0,
                        "inventory_status": "IN_STOCK",
                        "out_of_stock_threshold": 0.0,
                        "created_at": 1725365731.924224,
                        "created_at_milliseconds": 1725365731924,
                        "updated_at": 1725365731.924224,
                        "updated_at_milliseconds": 1725365731924,
                        "on_order_details": [
                            {
                                "quantity": 0.0,
                                "date": None,
                                "identifier": "on_order_0"
                            }
                        ],
                        "in_transit_details": [],
                        "notes": ""
                    },
                    "group_number": 0,
                    "group_name": "Ungrouped",
                    "priority": 10,
                    "raw_group_total": 0,
                    "group_total": "$ 0"
                },
                {
                    "ser_no": "11",
                    "image_url": "https://fileserver-g-p.sourcerer.tech/files/53f41f08-54e6-4081-b393-092484fce7b3?quality=20&transforms=%5B%5B%22resize%22%2C%7B%22width%22%3A100%2C%22height%22%3A100%2C%22background%22%3A%22white%22%2C%22fit%22%3A%22contain%22%7D%5D%5D",
                    "sku_id": "19472",
                    "name": "6888 Steamboat Fishing Bal Aprn",
                    "qty": 1,
                    "price": "$ 7.50",
                    "raw_price": 7.5,
                    "base_price": "$ 7.50",
                    "raw_base_price": 7.5,
                    "currency": "$",
                    "amount": "$ 7.50",
                    "raw_amount": 7.5,
                    "hinges_values": "",
                    "offered_price": "$ 7.50",
                    "raw_offered_price": 7.5,
                    "discount": "",
                    "note": "",
                    "is_custom_product": False,
                    "product_attributes": [],
                    "applied_modifiers": {},
                    "inventory": {
                        "inventory_tracking_enabled": False,
                        "available_quantity": 0.0,
                        "reserved_quantity": 0.0,
                        "in_stock_quantity": 0.0,
                        "backorder_allowed": False,
                        "backorder_available_quantity": 0,
                        "backorder_reserved_quantity": 0.0,
                        "on_order_quantity": 0.0,
                        "on_order_date": None,
                        "total_available": 0.0,
                        "total_reserved": 0.0,
                        "inventory_status": "IN_STOCK",
                        "out_of_stock_threshold": 0.0,
                        "created_at": 1725365731.924224,
                        "created_at_milliseconds": 1725365731924,
                        "updated_at": 1725365731.924224,
                        "updated_at_milliseconds": 1725365731924,
                        "on_order_details": [
                            {
                                "quantity": 0.0,
                                "date": None,
                                "identifier": "on_order_0"
                            }
                        ],
                        "in_transit_details": [],
                        "notes": ""
                    },
                    "group_number": 0,
                    "group_name": "Ungrouped",
                    "priority": 11,
                    "raw_group_total": 0,
                    "group_total": "$ 0"
                },
                {
                    "ser_no": "12",
                    "image_url": "https://fileserver-g-p.sourcerer.tech/files/68626c38-a6c7-4e50-a41d-f6f4f73c8f38?quality=20&transforms=%5B%5B%22resize%22%2C%7B%22width%22%3A100%2C%22height%22%3A100%2C%22background%22%3A%22white%22%2C%22fit%22%3A%22contain%22%7D%5D%5D",
                    "sku_id": "19552",
                    "name": "7670 Colonial Williamsburg Aprn",
                    "qty": 1,
                    "price": "$ 15.00",
                    "raw_price": 15.0,
                    "base_price": "$ 15.00",
                    "raw_base_price": 15.0,
                    "currency": "$",
                    "amount": "$ 15.00",
                    "raw_amount": 15.0,
                    "hinges_values": "",
                    "offered_price": "$ 15.00",
                    "raw_offered_price": 15.0,
                    "discount": "",
                    "note": "",
                    "is_custom_product": False,
                    "product_attributes": [],
                    "applied_modifiers": {},
                    "inventory": {
                        "inventory_tracking_enabled": False,
                        "available_quantity": 0.0,
                        "reserved_quantity": 0.0,
                        "in_stock_quantity": 0.0,
                        "backorder_allowed": False,
                        "backorder_available_quantity": 0,
                        "backorder_reserved_quantity": 0.0,
                        "on_order_quantity": 0.0,
                        "on_order_date": None,
                        "total_available": 0.0,
                        "total_reserved": 0.0,
                        "inventory_status": "IN_STOCK",
                        "out_of_stock_threshold": 0.0,
                        "created_at": 1725365731.924224,
                        "created_at_milliseconds": 1725365731924,
                        "updated_at": 1725365731.924224,
                        "updated_at_milliseconds": 1725365731924,
                        "on_order_details": [
                            {
                                "quantity": 0.0,
                                "date": None,
                                "identifier": "on_order_0"
                            }
                        ],
                        "in_transit_details": [],
                        "notes": ""
                    },
                    "group_number": 0,
                    "group_name": "Ungrouped",
                    "priority": 12,
                    "raw_group_total": 0,
                    "group_total": "$ 0"
                },
                {
                    "ser_no": "13",
                    "image_url": "https://fileserver-g-p.sourcerer.tech/files/46d2271c-e36c-4ae4-a6bf-9eb444bec18a?quality=20&transforms=%5B%5B%22resize%22%2C%7B%22width%22%3A100%2C%22height%22%3A100%2C%22background%22%3A%22white%22%2C%22fit%22%3A%22contain%22%7D%5D%5D",
                    "sku_id": "19553",
                    "name": "7687 Colonial Williamsburg Aprn",
                    "qty": 1,
                    "price": "$ 12.00",
                    "raw_price": 12.0,
                    "base_price": "$ 12.00",
                    "raw_base_price": 12.0,
                    "currency": "$",
                    "amount": "$ 12.00",
                    "raw_amount": 12.0,
                    "hinges_values": "",
                    "offered_price": "$ 12.00",
                    "raw_offered_price": 12.0,
                    "discount": "",
                    "note": "",
                    "is_custom_product": False,
                    "product_attributes": [],
                    "applied_modifiers": {},
                    "inventory": {
                        "inventory_tracking_enabled": False,
                        "available_quantity": 0.0,
                        "reserved_quantity": 0.0,
                        "in_stock_quantity": 0.0,
                        "backorder_allowed": False,
                        "backorder_available_quantity": 0,
                        "backorder_reserved_quantity": 0.0,
                        "on_order_quantity": 0.0,
                        "on_order_date": None,
                        "total_available": 0.0,
                        "total_reserved": 0.0,
                        "inventory_status": "IN_STOCK",
                        "out_of_stock_threshold": 0.0,
                        "created_at": 1725365731.924224,
                        "created_at_milliseconds": 1725365731924,
                        "updated_at": 1725365731.924224,
                        "updated_at_milliseconds": 1725365731924,
                        "on_order_details": [
                            {
                                "quantity": 0.0,
                                "date": None,
                                "identifier": "on_order_0"
                            }
                        ],
                        "in_transit_details": [],
                        "notes": ""
                    },
                    "group_number": 0,
                    "group_name": "Ungrouped",
                    "priority": 13,
                    "raw_group_total": 0,
                    "group_total": "$ 0"
                },
                {
                    "ser_no": "14",
                    "image_url": "https://fileserver-g-p.sourcerer.tech/files/ae5f1d2b-6ae8-4762-b9cd-0def197a67ee?quality=20&transforms=%5B%5B%22resize%22%2C%7B%22width%22%3A100%2C%22height%22%3A100%2C%22background%22%3A%22white%22%2C%22fit%22%3A%22contain%22%7D%5D%5D",
                    "sku_id": "19906",
                    "name": "0410 Colorado Distressed Apron",
                    "qty": 1,
                    "price": "$ 15.00",
                    "raw_price": 15.0,
                    "base_price": "$ 15.00",
                    "raw_base_price": 15.0,
                    "currency": "$",
                    "amount": "$ 15.00",
                    "raw_amount": 15.0,
                    "hinges_values": "",
                    "offered_price": "$ 15.00",
                    "raw_offered_price": 15.0,
                    "discount": "",
                    "note": "",
                    "is_custom_product": False,
                    "product_attributes": [],
                    "applied_modifiers": {},
                    "inventory": {
                        "inventory_tracking_enabled": False,
                        "available_quantity": 0.0,
                        "reserved_quantity": 0.0,
                        "in_stock_quantity": 0.0,
                        "backorder_allowed": False,
                        "backorder_available_quantity": 0,
                        "backorder_reserved_quantity": 0.0,
                        "on_order_quantity": 0.0,
                        "on_order_date": None,
                        "total_available": 0.0,
                        "total_reserved": 0.0,
                        "inventory_status": "IN_STOCK",
                        "out_of_stock_threshold": 0.0,
                        "created_at": 1725365731.924224,
                        "created_at_milliseconds": 1725365731924,
                        "updated_at": 1725365731.924224,
                        "updated_at_milliseconds": 1725365731924,
                        "on_order_details": [
                            {
                                "quantity": 0.0,
                                "date": None,
                                "identifier": "on_order_0"
                            }
                        ],
                        "in_transit_details": [],
                        "notes": ""
                    },
                    "group_number": 0,
                    "group_name": "Ungrouped",
                    "priority": 14,
                    "raw_group_total": 0,
                    "group_total": "$ 0"
                },
                {
                    "ser_no": "15",
                    "image_url": "https://fileserver-g-p.sourcerer.tech/files/926276f6-9a56-4be8-be8b-6d9026bfd752?quality=20&transforms=%5B%5B%22resize%22%2C%7B%22width%22%3A100%2C%22height%22%3A100%2C%22background%22%3A%22white%22%2C%22fit%22%3A%22contain%22%7D%5D%5D",
                    "sku_id": "19907",
                    "name": "0427 Colorado Distressed Apron",
                    "qty": 1,
                    "price": "$ 12.00",
                    "raw_price": 12.0,
                    "base_price": "$ 12.00",
                    "raw_base_price": 12.0,
                    "currency": "$",
                    "amount": "$ 12.00",
                    "raw_amount": 12.0,
                    "hinges_values": "",
                    "offered_price": "$ 12.00",
                    "raw_offered_price": 12.0,
                    "discount": "",
                    "note": "",
                    "is_custom_product": False,
                    "product_attributes": [],
                    "applied_modifiers": {},
                    "inventory": {
                        "inventory_tracking_enabled": False,
                        "available_quantity": 0.0,
                        "reserved_quantity": 0.0,
                        "in_stock_quantity": 0.0,
                        "backorder_allowed": False,
                        "backorder_available_quantity": 0,
                        "backorder_reserved_quantity": 0.0,
                        "on_order_quantity": 0.0,
                        "on_order_date": None,
                        "total_available": 0.0,
                        "total_reserved": 0.0,
                        "inventory_status": "IN_STOCK",
                        "out_of_stock_threshold": 0.0,
                        "created_at": 1725365731.924224,
                        "created_at_milliseconds": 1725365731924,
                        "updated_at": 1725365731.924224,
                        "updated_at_milliseconds": 1725365731924,
                        "on_order_details": [
                            {
                                "quantity": 0.0,
                                "date": None,
                                "identifier": "on_order_0"
                            }
                        ],
                        "in_transit_details": [],
                        "notes": ""
                    },
                    "group_number": 0,
                    "group_name": "Ungrouped",
                    "priority": 15,
                    "raw_group_total": 0,
                    "group_total": "$ 0"
                },
                {
                    "ser_no": "16",
                    "image_url": "https://fileserver-g-p.sourcerer.tech/files/5f1e0596-724b-463c-b5a7-f3c574158bf6?quality=20&transforms=%5B%5B%22resize%22%2C%7B%22width%22%3A100%2C%22height%22%3A100%2C%22background%22%3A%22white%22%2C%22fit%22%3A%22contain%22%7D%5D%5D",
                    "sku_id": "20143",
                    "name": "1585 Red Rocks Amphitheater Apr",
                    "qty": 1,
                    "price": "$ 7.50",
                    "raw_price": 7.5,
                    "base_price": "$ 7.50",
                    "raw_base_price": 7.5,
                    "currency": "$",
                    "amount": "$ 7.50",
                    "raw_amount": 7.5,
                    "hinges_values": "",
                    "offered_price": "$ 7.50",
                    "raw_offered_price": 7.5,
                    "discount": "",
                    "note": "",
                    "is_custom_product": False,
                    "product_attributes": [],
                    "applied_modifiers": {},
                    "inventory": {
                        "inventory_tracking_enabled": False,
                        "available_quantity": 0.0,
                        "reserved_quantity": 0.0,
                        "in_stock_quantity": 0.0,
                        "backorder_allowed": False,
                        "backorder_available_quantity": 0,
                        "backorder_reserved_quantity": 0.0,
                        "on_order_quantity": 0.0,
                        "on_order_date": None,
                        "total_available": 0.0,
                        "total_reserved": 0.0,
                        "inventory_status": "IN_STOCK",
                        "out_of_stock_threshold": 0.0,
                        "created_at": 1725365731.924224,
                        "created_at_milliseconds": 1725365731924,
                        "updated_at": 1725365731.924224,
                        "updated_at_milliseconds": 1725365731924,
                        "on_order_details": [
                            {
                                "quantity": 0.0,
                                "date": None,
                                "identifier": "on_order_0"
                            }
                        ],
                        "in_transit_details": [],
                        "notes": ""
                    },
                    "group_number": 0,
                    "group_name": "Ungrouped",
                    "priority": 16,
                    "raw_group_total": 0,
                    "group_total": "$ 0"
                },
                {
                    "ser_no": "17",
                    "image_url": "https://fileserver-g-p.sourcerer.tech/files/6827c9d9-7238-4612-bf6d-ad94d5ba7646?quality=20&transforms=%5B%5B%22resize%22%2C%7B%22width%22%3A100%2C%22height%22%3A100%2C%22background%22%3A%22white%22%2C%22fit%22%3A%22contain%22%7D%5D%5D",
                    "sku_id": "20156",
                    "name": "1820 Atlanta Botanical Garden A",
                    "qty": 1,
                    "price": "$ 7.50",
                    "raw_price": 7.5,
                    "base_price": "$ 7.50",
                    "raw_base_price": 7.5,
                    "currency": "$",
                    "amount": "$ 7.50",
                    "raw_amount": 7.5,
                    "hinges_values": "",
                    "offered_price": "$ 7.50",
                    "raw_offered_price": 7.5,
                    "discount": "",
                    "note": "",
                    "is_custom_product": False,
                    "product_attributes": [],
                    "applied_modifiers": {},
                    "inventory": {
                        "inventory_tracking_enabled": False,
                        "available_quantity": 0.0,
                        "reserved_quantity": 0.0,
                        "in_stock_quantity": 0.0,
                        "backorder_allowed": False,
                        "backorder_available_quantity": 0,
                        "backorder_reserved_quantity": 0.0,
                        "on_order_quantity": 0.0,
                        "on_order_date": None,
                        "total_available": 0.0,
                        "total_reserved": 0.0,
                        "inventory_status": "IN_STOCK",
                        "out_of_stock_threshold": 0.0,
                        "created_at": 1725365731.924224,
                        "created_at_milliseconds": 1725365731924,
                        "updated_at": 1725365731.924224,
                        "updated_at_milliseconds": 1725365731924,
                        "on_order_details": [
                            {
                                "quantity": 0.0,
                                "date": None,
                                "identifier": "on_order_0"
                            }
                        ],
                        "in_transit_details": [],
                        "notes": ""
                    },
                    "group_number": 0,
                    "group_name": "Ungrouped",
                    "priority": 17,
                    "raw_group_total": 0,
                    "group_total": "$ 0"
                },
                {
                    "ser_no": "18",
                    "image_url": "https://sourcerer.tech/assets/e79f8cf2-4639-4ed6-998f-6e5a393f510b",
                    "sku_id": "20587",
                    "name": "3992 Ole Smoky Black One Pocket",
                    "qty": 1,
                    "price": "$ 15.00",
                    "raw_price": 15.0,
                    "base_price": "$ 15.00",
                    "raw_base_price": 15.0,
                    "currency": "$",
                    "amount": "$ 15.00",
                    "raw_amount": 15.0,
                    "hinges_values": "",
                    "offered_price": "$ 15.00",
                    "raw_offered_price": 15.0,
                    "discount": "",
                    "note": "",
                    "is_custom_product": False,
                    "product_attributes": [],
                    "applied_modifiers": {},
                    "inventory": {
                        "inventory_tracking_enabled": False,
                        "available_quantity": 0.0,
                        "reserved_quantity": 0.0,
                        "in_stock_quantity": 0.0,
                        "backorder_allowed": False,
                        "backorder_available_quantity": 0,
                        "backorder_reserved_quantity": 0.0,
                        "on_order_quantity": 0.0,
                        "on_order_date": None,
                        "total_available": 0.0,
                        "total_reserved": 0.0,
                        "inventory_status": "IN_STOCK",
                        "out_of_stock_threshold": 0.0,
                        "created_at": 1725365731.924224,
                        "created_at_milliseconds": 1725365731924,
                        "updated_at": 1725365731.924224,
                        "updated_at_milliseconds": 1725365731924,
                        "on_order_details": [
                            {
                                "quantity": 0.0,
                                "date": None,
                                "identifier": "on_order_0"
                            }
                        ],
                        "in_transit_details": [],
                        "notes": ""
                    },
                    "group_number": 0,
                    "group_name": "Ungrouped",
                    "priority": 18,
                    "raw_group_total": 0,
                    "group_total": "$ 0"
                },
                {
                    "ser_no": "19",
                    "image_url": "https://fileserver-g-p.sourcerer.tech/files/37eff33c-70e5-4656-91c9-6d6f7d534ae1?quality=20&transforms=%5B%5B%22resize%22%2C%7B%22width%22%3A100%2C%22height%22%3A100%2C%22background%22%3A%22white%22%2C%22fit%22%3A%22contain%22%7D%5D%5D",
                    "sku_id": "20833",
                    "name": "6122 Shenandoah National Park E",
                    "qty": 1,
                    "price": "$ 7.50",
                    "raw_price": 7.5,
                    "base_price": "$ 7.50",
                    "raw_base_price": 7.5,
                    "currency": "$",
                    "amount": "$ 7.50",
                    "raw_amount": 7.5,
                    "hinges_values": "",
                    "offered_price": "$ 7.50",
                    "raw_offered_price": 7.5,
                    "discount": "",
                    "note": "",
                    "is_custom_product": False,
                    "product_attributes": [],
                    "applied_modifiers": {},
                    "inventory": {
                        "inventory_tracking_enabled": False,
                        "available_quantity": 0.0,
                        "reserved_quantity": 0.0,
                        "in_stock_quantity": 0.0,
                        "backorder_allowed": False,
                        "backorder_available_quantity": 0,
                        "backorder_reserved_quantity": 0.0,
                        "on_order_quantity": 0.0,
                        "on_order_date": None,
                        "total_available": 0.0,
                        "total_reserved": 0.0,
                        "inventory_status": "IN_STOCK",
                        "out_of_stock_threshold": 0.0,
                        "created_at": 1725365731.924224,
                        "created_at_milliseconds": 1725365731924,
                        "updated_at": 1725365731.924224,
                        "updated_at_milliseconds": 1725365731924,
                        "on_order_details": [
                            {
                                "quantity": 0.0,
                                "date": None,
                                "identifier": "on_order_0"
                            }
                        ],
                        "in_transit_details": [],
                        "notes": ""
                    },
                    "group_number": 0,
                    "group_name": "Ungrouped",
                    "priority": 19,
                    "raw_group_total": 0,
                    "group_total": "$ 0"
                },
                {
                    "ser_no": "20",
                    "image_url": "https://fileserver-g-p.sourcerer.tech/files/3962899a-0a98-4e77-95c3-36d19440e475?quality=20&transforms=%5B%5B%22resize%22%2C%7B%22width%22%3A100%2C%22height%22%3A100%2C%22background%22%3A%22white%22%2C%22fit%22%3A%22contain%22%7D%5D%5D",
                    "sku_id": "2998",
                    "name": "1075417 Georgetown Colorado",
                    "qty": 1,
                    "price": "$ 8.50",
                    "raw_price": 8.5,
                    "base_price": "$ 8.50",
                    "raw_base_price": 8.5,
                    "currency": "$",
                    "amount": "$ 8.50",
                    "raw_amount": 8.5,
                    "hinges_values": "",
                    "offered_price": "$ 8.50",
                    "raw_offered_price": 8.5,
                    "discount": "",
                    "note": "",
                    "is_custom_product": False,
                    "product_attributes": [],
                    "applied_modifiers": {},
                    "inventory": {
                        "inventory_tracking_enabled": False,
                        "available_quantity": 0.0,
                        "reserved_quantity": 0.0,
                        "in_stock_quantity": 0.0,
                        "backorder_allowed": False,
                        "backorder_available_quantity": 0,
                        "backorder_reserved_quantity": 0.0,
                        "on_order_quantity": 0.0,
                        "on_order_date": None,
                        "total_available": 0.0,
                        "total_reserved": 0.0,
                        "inventory_status": "IN_STOCK",
                        "out_of_stock_threshold": 0.0,
                        "created_at": 1725365731.924224,
                        "created_at_milliseconds": 1725365731924,
                        "updated_at": 1725365731.924224,
                        "updated_at_milliseconds": 1725365731924,
                        "on_order_details": [
                            {
                                "quantity": 0.0,
                                "date": None,
                                "identifier": "on_order_0"
                            }
                        ],
                        "in_transit_details": [],
                        "notes": ""
                    },
                    "group_number": 0,
                    "group_name": "Ungrouped",
                    "priority": 20,
                    "raw_group_total": 0,
                    "group_total": "$ 0"
                },
                {
                    "ser_no": "21",
                    "image_url": "https://fileserver-g-p.sourcerer.tech/files/63de6a04-7657-43a5-9317-9675c005f1f5?quality=20&transforms=%5B%5B%22resize%22%2C%7B%22width%22%3A100%2C%22height%22%3A100%2C%22background%22%3A%22white%22%2C%22fit%22%3A%22contain%22%7D%5D%5D",
                    "sku_id": "3260",
                    "name": "GL6199 Florida Keys",
                    "qty": 1,
                    "price": "$ 8.95",
                    "raw_price": 8.95,
                    "base_price": "$ 8.95",
                    "raw_base_price": 8.95,
                    "currency": "$",
                    "amount": "$ 8.95",
                    "raw_amount": 8.95,
                    "hinges_values": "",
                    "offered_price": "$ 8.95",
                    "raw_offered_price": 8.95,
                    "discount": "",
                    "note": "Test Check",
                    "is_custom_product": False,
                    "product_attributes": [],
                    "applied_modifiers": {},
                    "inventory": {
                        "inventory_tracking_enabled": False,
                        "available_quantity": 0.0,
                        "reserved_quantity": 0.0,
                        "in_stock_quantity": 0.0,
                        "backorder_allowed": False,
                        "backorder_available_quantity": 0,
                        "backorder_reserved_quantity": 0.0,
                        "on_order_quantity": 0.0,
                        "on_order_date": None,
                        "total_available": 0.0,
                        "total_reserved": 0.0,
                        "inventory_status": "IN_STOCK",
                        "out_of_stock_threshold": 0.0,
                        "created_at": 1725365731.924224,
                        "created_at_milliseconds": 1725365731924,
                        "updated_at": 1725365731.924224,
                        "updated_at_milliseconds": 1725365731924,
                        "on_order_details": [
                            {
                                "quantity": 0.0,
                                "date": None,
                                "identifier": "on_order_0"
                            }
                        ],
                        "in_transit_details": [],
                        "notes": ""
                    },
                    "group_number": 0,
                    "group_name": "Ungrouped",
                    "priority": 21,
                    "raw_group_total": 0,
                    "group_total": "$ 0"
                },
                {
                    "ser_no": "22",
                    "image_url": "https://fileserver-g-p.sourcerer.tech/files/2a4754ad-ce8f-48d8-b29f-0073e5007329?quality=20&transforms=%5B%5B%22resize%22%2C%7B%22width%22%3A100%2C%22height%22%3A100%2C%22background%22%3A%22white%22%2C%22fit%22%3A%22contain%22%7D%5D%5D",
                    "sku_id": "3545",
                    "name": "208 Alaska",
                    "qty": 1,
                    "price": "$ 5.50",
                    "raw_price": 5.5,
                    "base_price": "$ 5.50",
                    "raw_base_price": 5.5,
                    "currency": "$",
                    "amount": "$ 4.95",
                    "raw_amount": 4.95,
                    "hinges_values": "",
                    "offered_price": "$ 4.95",
                    "raw_offered_price": 4.95,
                    "discount": "10.00 %",
                    "note": "",
                    "is_custom_product": False,
                    "product_attributes": [],
                    "applied_modifiers": {},
                    "inventory": {
                        "inventory_tracking_enabled": False,
                        "available_quantity": 0.0,
                        "reserved_quantity": 0.0,
                        "in_stock_quantity": 0.0,
                        "backorder_allowed": False,
                        "backorder_available_quantity": 0,
                        "backorder_reserved_quantity": 0.0,
                        "on_order_quantity": 0.0,
                        "on_order_date": None,
                        "total_available": 0.0,
                        "total_reserved": 0.0,
                        "inventory_status": "IN_STOCK",
                        "out_of_stock_threshold": 0.0,
                        "created_at": 1725365731.924224,
                        "created_at_milliseconds": 1725365731924,
                        "updated_at": 1725365731.924224,
                        "updated_at_milliseconds": 1725365731924,
                        "on_order_details": [
                            {
                                "quantity": 0.0,
                                "date": None,
                                "identifier": "on_order_0"
                            }
                        ],
                        "in_transit_details": [],
                        "notes": ""
                    },
                    "group_number": 0,
                    "group_name": "Ungrouped",
                    "priority": 22,
                    "raw_group_total": 0,
                    "group_total": "$ 0"
                },
                {
                    "ser_no": "23",
                    "image_url": "https://fileserver-g-p.sourcerer.tech/files/8aec8c36-1a75-4768-b204-0bf73effd678?quality=20&transforms=%5B%5B%22resize%22%2C%7B%22width%22%3A100%2C%22height%22%3A100%2C%22background%22%3A%22white%22%2C%22fit%22%3A%22contain%22%7D%5D%5D",
                    "sku_id": "3312",
                    "name": "100507 Utah",
                    "qty": 1,
                    "price": "$ 8.95",
                    "raw_price": 8.95,
                    "base_price": "$ 8.95",
                    "raw_base_price": 8.95,
                    "currency": "$",
                    "amount": "$ 6.95",
                    "raw_amount": 6.949999999999999,
                    "hinges_values": "",
                    "offered_price": "$ 6.95",
                    "raw_offered_price": 6.95,
                    "discount": "$ 2.00",
                    "note": "",
                    "is_custom_product": False,
                    "product_attributes": [],
                    "applied_modifiers": {},
                    "inventory": {
                        "inventory_tracking_enabled": False,
                        "available_quantity": 0.0,
                        "reserved_quantity": 0.0,
                        "in_stock_quantity": 0.0,
                        "backorder_allowed": False,
                        "backorder_available_quantity": 0,
                        "backorder_reserved_quantity": 0.0,
                        "on_order_quantity": 0.0,
                        "on_order_date": None,
                        "total_available": 0.0,
                        "total_reserved": 0.0,
                        "inventory_status": "IN_STOCK",
                        "out_of_stock_threshold": 0.0,
                        "created_at": 1725365731.924224,
                        "created_at_milliseconds": 1725365731924,
                        "updated_at": 1725365731.924224,
                        "updated_at_milliseconds": 1725365731924,
                        "on_order_details": [
                            {
                                "quantity": 0.0,
                                "date": None,
                                "identifier": "on_order_0"
                            }
                        ],
                        "in_transit_details": [],
                        "notes": ""
                    },
                    "group_number": 0,
                    "group_name": "Ungrouped",
                    "priority": 23,
                    "raw_group_total": 0,
                    "group_total": "$ 0"
                }
            ],
            "description_attr_id": "00359252-f2a5-4e81-a756-4a20b3dc4d74",
            "website": "Www.artstudiocompany.com",
            "header": "Art Studio Company",
            "section_header": "Product Details",
            "img_logo": "https://ultronapi-g-p.sourcerer.tech/artifact/v1/file/439b5cfe-cb88-4735-a1a0-053d0dc98dbd",
            "tenant_address": "12290 Wilkins Ave. Rockville, MD 20852",
            "sample_file": None,
            "attrs_to_show": [],
            "customer_id": "#1234",
            "all_document_data": {
                "id": "ca254d2b-fe72-4982-883d-801c54fb86df",
                "system_id": "WC_00011",
                "reference_id": None,
                "source": "sales_rep",
                "offline_system_id": "",
                "type": "order",
                "tenant_id": "67cacc34-3702-432c-88f8-f43119b9b5b2",
                "created_by": "cc93c627-4b95-4a37-b759-b517438c48bd",
                "updated_by": "cc93c627-4b95-4a37-b759-b517438c48bd",
                "owner": "cc93c627-4b95-4a37-b759-b517438c48bd",
                "buyer_id": "82f5b1a4-716a-4ad7-ae86-1a5cdfaa55ed",
                "expired_at": None,
                "cart_id": "3588450b-e678-4b65-8310-ba563730e28a",
                "orignal_order_id": "f9c81123-cdcb-43c0-b11f-a53f295124cd",
                "date": None,
                "document_status": "confirmed",
                "total_value": 276.75,
                "payment_due_date": None,
                "payment_transaction_id": None,
                "payment_transaction_details": None,
                "payment_status": "PENDING",
                "attributes": {
                    "a7d79b6e-9480-4451-89ae-48155d91f018": "90999",
                    "68cd9b05-cc8c-4f75-a218-d70a839be71c": "#1234",
                    "billing_address": {
                        "id": "a4aa16fb-22c1-4d51-b23e-549b4952cf0e",
                        "first_name": "John",
                        "last_name": "Mac",
                        "country_code": "+1",
                        "phone": "9048922912",
                        "email": "Johnmac@wizcommerce.com",
                        "city": "Bangor",
                        "state": "MI",
                        "country": "USA",
                        "pincode": "48150",
                        "street_address": "14th Street, Penobscot County",
                        "address_line_2": "New York County",
                        "reference_id": "",
                        "attribute_values": []
                    },
                    "shipping_address": {
                        "id": "b3ef825f-e1bb-4e08-967c-b8b5985a80d8",
                        "first_name": "John",
                        "last_name": "Mac",
                        "country_code": "+1",
                        "phone": "9048922912",
                        "email": "Johnmac@wizcommerce.com",
                        "city": "New York",
                        "state": "New York",
                        "country": "USA",
                        "pincode": "10038",
                        "street_address": "123 William St",
                        "address_line_2": "New York County",
                        "reference_id": "",
                        "attribute_values": []
                    },
                    "payment_method": "",
                    "payment_method_id": None,
                    "payment_terms": "",
                    "freight_terms": "",
                    "notification_email_ids": [
                        "Johnmac@wizcommerce.com"
                    ],
                    "shipping_method": "",
                    "primary_contact": {
                        "id": "6cd35151-5f28-459f-84e3-464ad1fcd705",
                        "email": "Johnmac@wizcommerce.com",
                        "phone": "9199999999",
                        "country_code": "+1",
                        "first_name": "John",
                        "last_name": "Mac",
                        "designation": "CEO",
                        "reference_id": ""
                    },
                    "shipping_terms": None,
                    "vendor_po": None,
                    "customer_po": None,
                    "carrier_name": None,
                    "carrier_service": None,
                    "date_scheduled": None,
                    "date_issued": None,
                    "auto_charges_calculation_enabled": False,
                    "customer_consent": False,
                    "signature": None,
                    "written_for": "cc93c627-4b95-4a37-b759-b517438c48bd",
                    "written_by": "cc93c627-4b95-4a37-b759-b517438c48bd",
                    "email_history": [],
                    "notes_settings": {
                        "my_notes": {
                            "notes": "Test Check",
                            "share_this_note_with_buyer": True
                        },
                        "customer_notes": {
                            "notes": "Test Check",
                            "share_this_note_with_buyer": True
                        }
                    },
                    "payment_method_v2": {}
                },
                "fulfillment_status": "UNFULFILLED",
                "fulfillment_details": None,
                "total_payment_received": None,
                "refund_details": None,
                "last_synced_with_source_at": None,
                "customer_consent": False,
                "signature": None,
                "entity_source": "wizorder",
                "is_sync": False,
                "last_sync_at": None,
                "last_sync_status": None,
                "last_sync_message": None,
                "reporting_attribute_1": None,
                "reporting_attribute_2": None,
                "reporting_attribute_3": None,
                "exported_date": None,
                "exported_method": None,
                "created_at": "01/13/2025",
                "updated_at": "2025-01-24T13:01:32.497453",
                "status": "published",
                "child": {},
                "charges": [
                    {
                        "id": "bee4f96c-a018-41d0-9d20-bd8bb17dbb52",
                        "name": "Discount",
                        "value_type": "percentage",
                        "value": 12.0,
                        "meta": {},
                        "charge_type": "discount",
                        "document_id": "ca254d2b-fe72-4982-883d-801c54fb86df"
                    },
                    {
                        "id": "bb2e5579-21fe-4315-90a0-7c2b51328a7c",
                        "name": "Shipping",
                        "value_type": "value",
                        "value": 100.0,
                        "meta": {},
                        "charge_type": "tax",
                        "document_id": "ca254d2b-fe72-4982-883d-801c54fb86df"
                    }
                ],
                "total_amount_due": 276.75,
                "all_payment_received_total": 0,
                "all_payment_refunded_total": 0,
                "excess_payment_received": 0,
                "created_by_name": "Art Studio Company",
                "created_by_email": "artstudio@wizcommerce.com",
                "created_by_phone": "9048922912",
                "created_by_department": "",
                "updated_by_name": "Art Studio Company",
                "updated_by_email": "artstudio@wizcommerce.com",
                "updated_by_phone": "9048922912",
                "updated_by_department": "",
                "written_by_name": "Art Studio Company",
                "written_by_email": "artstudio@wizcommerce.com",
                "written_by_phone": "9048922912",
                "written_by_department": "",
                "written_for_name": "Art Studio Company",
                "written_for_email": "artstudio@wizcommerce.com",
                "written_for_phone": "9048922912",
                "written_for_department": "",
                "sales_rep_name": "Art Studio Company",
                "sales_rep_email": "artstudio@wizcommerce.com",
                "sales_rep_phone": "9048922912",
                "sales_rep_department": "",
                "catalog_name": "Sales Price",
                "claim_form_added": False
            },
            "transactions": {
                "transactions": [],
                "invoices": [],
                "total_authorized_amount": 0
            },
            "buyer_details": {
                "id": "82f5b1a4-716a-4ad7-ae86-1a5cdfaa55ed",
                "name": "Wizcommerce Test",
                "reference_id": None,
                "type_of_customer": None,
                "sales_rep": "Art Studio Company",
                "sales_rep_email": "artstudio@wizcommerce.com",
                "sales_rep_phone": "9048922912",
                "sales_rep_department": "",
                "buyer_group": None,
                "location": "Bangor, USA",
                "contact_person_name": "John Mac",
                "label": {
                    "background_color": "",
                    "text_color": "",
                    "text": ""
                },
                "primary_contact": {
                    "email": "Johnmac@wizcommerce.com",
                    "phone": "9199999999",
                    "country_code": "+1"
                },
                "payment_method": {},
                "wallet_balance": 0.0,
                "analytics": {
                    "today": {
                        "total_revenue": {
                            "value": "6,200",
                            "percentage": "100%",
                            "orders": 2,
                            "quotes": 5
                        },
                        "total_orders": {
                            "value": "2",
                            "biggest_order": "4,000"
                        },
                        "total_quotes": {
                            "value": "5",
                            "biggest_quote": "ABC",
                            "biggest_quote_value": "13,450"
                        },
                        "total_drafts": {
                            "value": "16",
                            "orders": 10,
                            "quotes": 6
                        }
                    },
                    "last_week": {},
                    "last_30_days": {},
                    "last_6_months": {},
                    "last_12_months": {},
                    "all_time": {}
                },
                "recent_orders": [
                    {
                        "date": "12 Aug 2023",
                        "type": "sent",
                        "id": 123456789,
                        "items": 12,
                        "price": "4,000",
                        "label": {
                            "background_color": "",
                            "text_color": "",
                            "text": ""
                        }
                    },
                    {
                        "date": "12 Aug 2023",
                        "type": "sent",
                        "id": 123456789,
                        "items": 12,
                        "price": "2,200"
                    }
                ]
            },
            "buyer_attributes": [
                {
                    "id": "f841c0ad-afbe-46e5-b8f5-21a586a97481",
                    "name": "Customer ID",
                    "type": "text",
                    "value": "123456",
                    "priority": 0,
                    "required": False,
                    "is_display": True,
                    "options": [],
                    "updated_at": "2024-09-03T17:03:20.583930",
                    "created_at": "2024-09-03T17:03:20.583930",
                    "is_display_exclusion_type": [],
                    "required_exclusion_type": [],
                    "validations": {},
                    "is_label_display": False
                }
            ],
            "contact_attributes": {},
            "address_attributes": {},
            "signature": "",
            "document_status": "confirmed",
            "document_created_by_name": "Art Studio Company",
            "document_created_by_email": "artstudio@wizcommerce.com",
            "document_created_by_phone": "9048922912",
            "document_created_by_department": "",
            "document_updated_by_name": "Art Studio Company",
            "document_updated_by_email": "artstudio@wizcommerce.com",
            "document_updated_by_phone": "9048922912",
            "document_updated_by_department": "",
            "document_sales_rep": "Art Studio Company",
            "document_sales_rep_email": "artstudio@wizcommerce.com",
            "document_sales_rep_phone": "9048922912",
            "document_sales_rep_department": "",
            "timezone": "America/New_York",
            "timezone_code": "EST",
            "po_number": "90999"
        }