data= {
    "system_id": "WC_01005",
    "buyer_name": "Vintage Boho Bags",
    "doc_type": "Order",
    "buyer_contact_first_name": "Michelle",
    "buyer_contact_last_name": "Miller",
    "document_written_for_name": "Omar A.",
    "document_written_for_email": "indiantouchofgallup@msn.com",
    "document_written_for_phone": "5058706364",
    "document_written_for_department": "CEO",
    "document_written_by_name": "Nemo",
    "document_written_by_email": "nativecityjewelry@gmail.com",
    "document_written_by_phone": "5059061382",
    "document_written_by_department": "",
    "buyer_contact_designation": "",
    "buyer_location": "Santa Maria, usa",
    "buyer_email": "mich.g.miller@gmail.com",
    "buyer_phone": "8052606868",
    "shipping_method": "",
    "shipping_terms": None,
    "payment_method": "",
    "payment_terms": "",
    "carrier_name": None,
    "freight_terms": "",
    "payment_status": "PENDING",
    "payment_status_label": "Payment Pending",
    "cart_total": "$ 132027.50",
    "total": "$ 132027.50",
    "total_amount_due": "$ 132027.50",
    "total_payment_received": "$ 0.00",
    "all_payment_received_total": "$ 0.00",
    "all_payment_refunded_total": "$ 0.00",
    "excess_payment_received": "$ 0.00",
    "date": "11/11/2024",
    "date_scheduled": "",
    "date_issued": "",
    "vendor_po": None,
    "customer_po": None,
    "charges": [
        {
            "charge_name": "Shipping chagres",
            "charge_value": "$ 220.00",
            "percentage": "20%"
        }
    ],
    "shipping_address": {
        "id": "1333fa8e-7285-46c1-96e1-72b010166a49",
        "first_name": "Vintage",
        "last_name": "Boho ",
        "country_code": "",
        "phone": "",
        "email": "",
        "city": "Santa Maria",
        "state": "California",
        "country": "United States of America",
        "pincode": "93455",
        "street_address": "275 W Waller Ln",
        "address_line_2": "",
        "reference_id": "",
        "attribute_values": []
    },
    "billing_address": {
        "id": "18becbd0-bd9e-4414-9c35-6fec33fd7f1c",
        "first_name": "",
        "last_name": "",
        "country_code": "",
        "phone": "",
        "email": "",
        "city": "Santa Maria",
        "state": "California",
        "country": "United States of America",
        "pincode": "93455",
        "street_address": "275 W Waller Ln",
        "address_line_2": "",
        "reference_id": "",
        "attribute_values": []
    },
    "customer_notes": "customer notes tushar added",
    "user_notes": "",
    "products": [
        {
            "ser_no": "1",
            "image_url": "https://sourcerer.tech/assets/1fd851bc-6fd3-4ed7-a4df-099b108d4819?quality=20&transforms=%5B%5B%22resize%22%2C%7B%22width%22%3A100%2C%22height%22%3A100%2C%22background%22%3A%22white%22%2C%22fit%22%3A%22contain%22%7D%5D%5D",
            "sku_id": "CUSTOM-00001",
            "name": "HADA TURQUOISE EARRINGS 5 STONE",
            "qty": 25,
            "price": "$ 49.50",
            "raw_price": 49.5,
            "currency": "$",
            "amount": "$ 1237.50",
            "raw_amount": 1237.5,
            "hinges_values": "",
            "offered_price": "$ 49.50",
            "raw_offered_price": 49.5,
            "discount": "",
            "note": "",
            "is_custom_product": False,
            "product_attributes": [],
            "applied_modifiers": {},
            "inventory": {
                "inventory_tracking_enabled": False
            },
            "group_number": 0,
            "group_name": "Ungrouped",
            "priority": 1,
            "raw_group_total": 0,
            "group_total": "$ 0"
        },
        {
            "ser_no": "2",
            "image_url": "https://sourcerer.tech/assets/1fd851bc-6fd3-4ed7-a4df-099b108d4819?quality=20&transforms=%5B%5B%22resize%22%2C%7B%22width%22%3A100%2C%22height%22%3A100%2C%22background%22%3A%22white%22%2C%22fit%22%3A%22contain%22%7D%5D%5D",
            "sku_id": "CUSTOM-00001",
            "name": "5MM PEARL 60''",
            "qty": 20,
            "price": "$ 143.00",
            "raw_price": 143.0,
            "currency": "$",
            "amount": "$ 2860.00",
            "raw_amount": 2860.0,
            "hinges_values": "",
            "offered_price": "$ 143.00",
            "raw_offered_price": 143.0,
            "discount": "",
            "note": "",
            "is_custom_product": False,
            "product_attributes": [],
            "applied_modifiers": {},
            "inventory": {
                "inventory_tracking_enabled": False
            },
            "group_number": 0,
            "group_name": "Ungrouped",
            "priority": 2,
            "raw_group_total": 0,
            "group_total": "$ 0"
        },
        {
            "ser_no": "3",
            "image_url": "https://fileserver-g-p.sourcerer.tech/files/b7f05e4c-3560-4088-bc3b-164317359955?quality=20&transforms=%5B%5B%22resize%22%2C%7B%22width%22%3A100%2C%22height%22%3A100%2C%22background%22%3A%22white%22%2C%22fit%22%3A%22contain%22%7D%5D%5D",
            "sku_id": "NK-000559",
            "name": "Handstrung Sterling Silver 4-8MM 16 Inch Pearl Beads Necklace",
            "qty": 100,
            "price": "$ 44.00",
            "raw_price": 44.0,
            "currency": "$",
            "amount": "$ 4400.00",
            "raw_amount": 4400.0,
            "hinges_values": "",
            "offered_price": "$ 44.00",
            "raw_offered_price": 44.0,
            "discount": "",
            "note": "",
            "is_custom_product": False,
            "product_attributes": [],
            "applied_modifiers": {},
            "inventory": {
                "inventory_tracking_enabled": True,
                "available_quantity": 996.0,
                "reserved_quantity": 4.0,
                "in_stock_quantity": 1000.0,
                "backorder_allowed": False,
                "backorder_available_quantity": 0,
                "backorder_reserved_quantity": 0.0,
                "on_order_quantity": 100.0,
                "on_order_date": None,
                "total_available": 996.0,
                "total_reserved": 4.0,
                "inventory_status": "IN_STOCK",
                "out_of_stock_threshold": 0.0,
                "created_at": 1700902945.557776,
                "created_at_milliseconds": 1700902945557,
                "updated_at": 1725124059.023771,
                "updated_at_milliseconds": 1725124059023,
                "on_order_details": [
                    {
                        "quantity": 100,
                        "date": None,
                        "identifier": "on_order_0"
                    }
                ],
                "in_transit_details": [
                    {
                        "quantity": 0,
                        "date": None,
                        "identifier": "in_transit_0"
                    }
                ],
                "notes": ""
            },
            "group_number": 0,
            "group_name": "Ungrouped",
            "priority": 3,
            "raw_group_total": 0,
            "group_total": "$ 0"
        },
        {
            "ser_no": "4",
            "image_url": "https://fileserver-g-p.sourcerer.tech/files/9cbe5730-62f3-4af0-8d61-bd9b45e4e40a?quality=20&transforms=%5B%5B%22resize%22%2C%7B%22width%22%3A100%2C%22height%22%3A100%2C%22background%22%3A%22white%22%2C%22fit%22%3A%22contain%22%7D%5D%5D",
            "sku_id": "NK-000560",
            "name": "Handstrung Sterling Silver 4-8MM 20 Inch Pearl Beads Necklace",
            "qty": 100,
            "price": "$ 55.00",
            "raw_price": 55.0,
            "currency": "$",
            "amount": "$ 5500.00",
            "raw_amount": 5500.0,
            "hinges_values": "",
            "offered_price": "$ 55.00",
            "raw_offered_price": 55.0,
            "discount": "",
            "note": "",
            "is_custom_product": False,
            "product_attributes": [],
            "applied_modifiers": {},
            "inventory": {
                "inventory_tracking_enabled": True,
                "available_quantity": 997.0,
                "reserved_quantity": 3.0,
                "in_stock_quantity": 1000.0,
                "backorder_allowed": False,
                "backorder_available_quantity": 0,
                "backorder_reserved_quantity": 0.0,
                "on_order_quantity": 100.0,
                "on_order_date": None,
                "total_available": 997.0,
                "total_reserved": 3.0,
                "inventory_status": "IN_STOCK",
                "out_of_stock_threshold": 0.0,
                "created_at": 1700902945.557776,
                "created_at_milliseconds": 1700902945557,
                "updated_at": 1727295913.664388,
                "updated_at_milliseconds": 1727295913664,
                "on_order_details": [
                    {
                        "quantity": 100,
                        "date": None,
                        "identifier": "on_order_0"
                    }
                ],
                "in_transit_details": [
                    {
                        "quantity": 0,
                        "date": None,
                        "identifier": "in_transit_0"
                    }
                ],
                "notes": ""
            },
            "group_number": 0,
            "group_name": "Ungrouped",
            "priority": 4,
            "raw_group_total": 0,
            "group_total": "$ 0"
        },
        {
            "ser_no": "5",
            "image_url": "https://fileserver-g-p.sourcerer.tech/files/25e9ae31-e46f-4109-9ad3-e0b6cd79ff3e?quality=20&transforms=%5B%5B%22resize%22%2C%7B%22width%22%3A100%2C%22height%22%3A100%2C%22background%22%3A%22white%22%2C%22fit%22%3A%22contain%22%7D%5D%5D",
            "sku_id": "ER-001493",
            "name": "Hada Collection Kingman Turquoise Earrings",
            "qty": 60,
            "price": "$ 77.00",
            "raw_price": 77.0,
            "currency": "$",
            "amount": "$ 4620.00",
            "raw_amount": 4620.0,
            "hinges_values": "",
            "offered_price": "$ 77.00",
            "raw_offered_price": 77.0,
            "discount": "",
            "note": "",
            "is_custom_product": False,
            "product_attributes": [],
            "applied_modifiers": {},
            "inventory": {
                "inventory_tracking_enabled": True,
                "available_quantity": 1000.0,
                "reserved_quantity": 0.0,
                "in_stock_quantity": 1000.0,
                "backorder_allowed": False,
                "backorder_available_quantity": 0,
                "backorder_reserved_quantity": 0.0,
                "on_order_quantity": 100.0,
                "on_order_date": None,
                "total_available": 1000.0,
                "total_reserved": 0.0,
                "inventory_status": "IN_STOCK",
                "out_of_stock_threshold": 0.0,
                "created_at": 1715726967.124862,
                "created_at_milliseconds": 1715726967124,
                "updated_at": 1716245416.949774,
                "updated_at_milliseconds": 1716245416949,
                "on_order_details": [
                    {
                        "quantity": 100,
                        "date": None,
                        "identifier": "on_order_0"
                    }
                ],
                "in_transit_details": [
                    {
                        "quantity": 0,
                        "date": None,
                        "identifier": "in_transit_0"
                    }
                ],
                "notes": ""
            },
            "group_number": 0,
            "group_name": "Ungrouped",
            "priority": 5,
            "raw_group_total": 0,
            "group_total": "$ 0"
        },
        {
            "ser_no": "6",
            "image_url": "https://fileserver-g-p.sourcerer.tech/files/8d8b6cfb-3674-4775-9e10-a9ecff1458aa?quality=20&transforms=%5B%5B%22resize%22%2C%7B%22width%22%3A100%2C%22height%22%3A100%2C%22background%22%3A%22white%22%2C%22fit%22%3A%22contain%22%7D%5D%5D",
            "sku_id": "RG-000888",
            "name": "Navajo Handmade Kingman Turquoise Ring - Davin Benally",
            "qty": 100,
            "price": "$ 66.00",
            "raw_price": 66.0,
            "currency": "$",
            "amount": "$ 6600.00",
            "raw_amount": 6600.0,
            "hinges_values": "",
            "offered_price": "$ 66.00",
            "raw_offered_price": 66.0,
            "discount": "",
            "note": "8.5",
            "is_custom_product": False,
            "product_attributes": [],
            "applied_modifiers": {},
            "inventory": {
                "inventory_tracking_enabled": True,
                "available_quantity": 1000.0,
                "reserved_quantity": 0.0,
                "in_stock_quantity": 1000.0,
                "backorder_allowed": False,
                "backorder_available_quantity": 0,
                "backorder_reserved_quantity": 0.0,
                "on_order_quantity": 100.0,
                "on_order_date": None,
                "total_available": 1000.0,
                "total_reserved": 0.0,
                "inventory_status": "IN_STOCK",
                "out_of_stock_threshold": 0.0,
                "created_at": 1711580206.275136,
                "created_at_milliseconds": 1711580206275,
                "updated_at": 1716245416.949774,
                "updated_at_milliseconds": 1716245416949,
                "on_order_details": [
                    {
                        "quantity": 100,
                        "date": None,
                        "identifier": "on_order_0"
                    }
                ],
                "in_transit_details": [
                    {
                        "quantity": 0,
                        "date": None,
                        "identifier": "in_transit_0"
                    }
                ],
                "notes": ""
            },
            "group_number": 0,
            "group_name": "Ungrouped",
            "priority": 6,
            "raw_group_total": 0,
            "group_total": "$ 0"
        },
        {
            "ser_no": "7",
            "image_url": "https://fileserver-g-p.sourcerer.tech/files/0202f56b-a217-40ab-8817-a82b3db8d6da?quality=20&transforms=%5B%5B%22resize%22%2C%7B%22width%22%3A100%2C%22height%22%3A100%2C%22background%22%3A%22white%22%2C%22fit%22%3A%22contain%22%7D%5D%5D",
            "sku_id": "ER-001491",
            "name": "Hada Collection Kingman Turquoise Earrings",
            "qty": 75,
            "price": "$ 88.00",
            "raw_price": 88.0,
            "currency": "$",
            "amount": "$ 6600.00",
            "raw_amount": 6600.0,
            "hinges_values": "",
            "offered_price": "$ 88.00",
            "raw_offered_price": 88.0,
            "discount": "",
            "note": "",
            "is_custom_product": False,
            "product_attributes": [],
            "applied_modifiers": {},
            "inventory": {
                "inventory_tracking_enabled": True,
                "available_quantity": 1000.0,
                "reserved_quantity": 0.0,
                "in_stock_quantity": 1000.0,
                "backorder_allowed": False,
                "backorder_available_quantity": 0,
                "backorder_reserved_quantity": 0.0,
                "on_order_quantity": 100.0,
                "on_order_date": None,
                "total_available": 1000.0,
                "total_reserved": 0.0,
                "inventory_status": "IN_STOCK",
                "out_of_stock_threshold": 0.0,
                "created_at": 1715726967.124862,
                "created_at_milliseconds": 1715726967124,
                "updated_at": 1716245416.949774,
                "updated_at_milliseconds": 1716245416949,
                "on_order_details": [
                    {
                        "quantity": 100,
                        "date": None,
                        "identifier": "on_order_0"
                    }
                ],
                "in_transit_details": [
                    {
                        "quantity": 0,
                        "date": None,
                        "identifier": "in_transit_0"
                    }
                ],
                "notes": ""
            },
            "group_number": 0,
            "group_name": "Ungrouped",
            "priority": 7,
            "raw_group_total": 0,
            "group_total": "$ 0"
        },
        {
            "ser_no": "8",
            "image_url": "https://fileserver-g-p.sourcerer.tech/files/ddbd2f5b-b278-44d4-a4b9-d322b73bbcbc?quality=20&transforms=%5B%5B%22resize%22%2C%7B%22width%22%3A100%2C%22height%22%3A100%2C%22background%22%3A%22white%22%2C%22fit%22%3A%22contain%22%7D%5D%5D",
            "sku_id": "NK-001061",
            "name": "Handstrung Sterling Silver 5MM 24 Inch Pearl Beads Necklace",
            "qty": 300,
            "price": "$ 60.50",
            "raw_price": 60.5,
            "currency": "$",
            "amount": "$ 18150.00",
            "raw_amount": 18150.0,
            "hinges_values": "",
            "offered_price": "$ 60.50",
            "raw_offered_price": 60.5,
            "discount": "",
            "note": "",
            "is_custom_product": False,
            "product_attributes": [],
            "applied_modifiers": {},
            "inventory": {
                "inventory_tracking_enabled": True,
                "available_quantity": 1000.0,
                "reserved_quantity": 0.0,
                "in_stock_quantity": 1000.0,
                "backorder_allowed": False,
                "backorder_available_quantity": 0,
                "backorder_reserved_quantity": 0.0,
                "on_order_quantity": 100.0,
                "on_order_date": None,
                "total_available": 1000.0,
                "total_reserved": 0.0,
                "inventory_status": "IN_STOCK",
                "out_of_stock_threshold": 0.0,
                "created_at": 1716329296.018697,
                "created_at_milliseconds": 1716329296018,
                "updated_at": 1716331287.543191,
                "updated_at_milliseconds": 1716331287543,
                "on_order_details": [
                    {
                        "quantity": 100,
                        "date": None,
                        "identifier": "on_order_0"
                    }
                ],
                "in_transit_details": [
                    {
                        "quantity": 0,
                        "date": None,
                        "identifier": "in_transit_0"
                    }
                ],
                "notes": ""
            },
            "group_number": 0,
            "group_name": "Ungrouped",
            "priority": 8,
            "raw_group_total": 0,
            "group_total": "$ 0"
        },
        {
            "ser_no": "9",
            "image_url": "https://sourcerer.tech/assets/1fd851bc-6fd3-4ed7-a4df-099b108d4819?quality=20&transforms=%5B%5B%22resize%22%2C%7B%22width%22%3A100%2C%22height%22%3A100%2C%22background%22%3A%22white%22%2C%22fit%22%3A%22contain%22%7D%5D%5D",
            "sku_id": "CUSTOM-00001",
            "name": "5MM 30'' PEARL",
            "qty": 300,
            "price": "$ 71.50",
            "raw_price": 71.5,
            "currency": "$",
            "amount": "$ 21450.00",
            "raw_amount": 21450.0,
            "hinges_values": "",
            "offered_price": "$ 71.50",
            "raw_offered_price": 71.5,
            "discount": "",
            "note": "",
            "is_custom_product": False,
            "product_attributes": [],
            "applied_modifiers": {},
            "inventory": {
                "inventory_tracking_enabled": False
            },
            "group_number": 0,
            "group_name": "Ungrouped",
            "priority": 9,
            "raw_group_total": 0,
            "group_total": "$ 0"
        },
        {
            "ser_no": "10",
            "image_url": "https://sourcerer.tech/assets/1fd851bc-6fd3-4ed7-a4df-099b108d4819?quality=20&transforms=%5B%5B%22resize%22%2C%7B%22width%22%3A100%2C%22height%22%3A100%2C%22background%22%3A%22white%22%2C%22fit%22%3A%22contain%22%7D%5D%5D",
            "sku_id": "CUSTOM-00001",
            "name": "HADA EARRING STRAIGHT 8 STONE",
            "qty": 200,
            "price": "$ 66.00",
            "raw_price": 66.0,
            "currency": "$",
            "amount": "$ 13200.00",
            "raw_amount": 13200.0,
            "hinges_values": "",
            "offered_price": "$ 66.00",
            "raw_offered_price": 66.0,
            "discount": "",
            "note": "",
            "is_custom_product": False,
            "product_attributes": [],
            "applied_modifiers": {},
            "inventory": {
                "inventory_tracking_enabled": False
            },
            "group_number": 0,
            "group_name": "Ungrouped",
            "priority": 10,
            "raw_group_total": 0,
            "group_total": "$ 0"
        },
        {
            "ser_no": "11",
            "image_url": "https://fileserver-g-p.sourcerer.tech/files/e5c3af05-d9cf-4ce4-92f0-7b191104b87f?quality=20&transforms=%5B%5B%22resize%22%2C%7B%22width%22%3A100%2C%22height%22%3A100%2C%22background%22%3A%22white%22%2C%22fit%22%3A%22contain%22%7D%5D%5D",
            "sku_id": "NK-001370",
            "name": "Hada Collection Kingman Turquoise Necklace",
            "qty": 500,
            "price": "$ 27.50",
            "raw_price": 27.5,
            "currency": "$",
            "amount": "$ 13750.00",
            "raw_amount": 13750.0,
            "hinges_values": "",
            "offered_price": "$ 27.50",
            "raw_offered_price": 27.5,
            "discount": "",
            "note": "",
            "is_custom_product": False,
            "product_attributes": [],
            "applied_modifiers": {},
            "inventory": {
                "inventory_tracking_enabled": False,
                "available_quantity": 0.0,
                "reserved_quantity": 0.0,
                "in_stock_quantity": 0.0,
                "backorder_allowed": False,
                "backorder_available_quantity": 0,
                "backorder_reserved_quantity": 0.0,
                "on_order_quantity": 0.0,
                "on_order_date": None,
                "total_available": 0.0,
                "total_reserved": 0.0,
                "inventory_status": "IN_STOCK",
                "out_of_stock_threshold": 0.0,
                "created_at": 1724967197.916887,
                "created_at_milliseconds": 1724967197916,
                "updated_at": 1724967197.916887,
                "updated_at_milliseconds": 1724967197916,
                "on_order_details": [
                    {
                        "quantity": 0.0,
                        "date": None,
                        "identifier": "on_order_0"
                    }
                ],
                "in_transit_details": [],
                "notes": ""
            },
            "group_number": 0,
            "group_name": "Ungrouped",
            "priority": 11,
            "raw_group_total": 0,
            "group_total": "$ 0"
        },
        {
            "ser_no": "12",
            "image_url": "https://fileserver-g-p.sourcerer.tech/files/697f5f9c-34aa-4298-84ab-e3b21f680cab?quality=20&transforms=%5B%5B%22resize%22%2C%7B%22width%22%3A100%2C%22height%22%3A100%2C%22background%22%3A%22white%22%2C%22fit%22%3A%22contain%22%7D%5D%5D",
            "sku_id": "ER-001917",
            "name": "Hada Collection Kingman Turquoise Earrings",
            "qty": 200,
            "price": "$ 33.00",
            "raw_price": 33.0,
            "currency": "$",
            "amount": "$ 6600.00",
            "raw_amount": 6600.0,
            "hinges_values": "",
            "offered_price": "$ 33.00",
            "raw_offered_price": 33.0,
            "discount": "",
            "note": "SHARK TOOTH BEZEL",
            "is_custom_product": False,
            "product_attributes": [],
            "applied_modifiers": {},
            "inventory": {
                "inventory_tracking_enabled": False,
                "available_quantity": 0.0,
                "reserved_quantity": 0.0,
                "in_stock_quantity": 0.0,
                "backorder_allowed": False,
                "backorder_available_quantity": 0,
                "backorder_reserved_quantity": 0.0,
                "on_order_quantity": 0.0,
                "on_order_date": None,
                "total_available": 0.0,
                "total_reserved": 0.0,
                "inventory_status": "IN_STOCK",
                "out_of_stock_threshold": 0.0,
                "created_at": 1726002288.758588,
                "created_at_milliseconds": 1726002288758,
                "updated_at": 1726002288.758588,
                "updated_at_milliseconds": 1726002288758,
                "on_order_details": [
                    {
                        "quantity": 0.0,
                        "date": None,
                        "identifier": "on_order_0"
                    }
                ],
                "in_transit_details": [],
                "notes": ""
            },
            "group_number": 0,
            "group_name": "Ungrouped",
            "priority": 12,
            "raw_group_total": 0,
            "group_total": "$ 0"
        },
        {
            "ser_no": "13",
            "image_url": "https://fileserver-g-p.sourcerer.tech/files/eaf68df4-d9cd-49f9-87c7-d790ceecff93?quality=20&transforms=%5B%5B%22resize%22%2C%7B%22width%22%3A100%2C%22height%22%3A100%2C%22background%22%3A%22white%22%2C%22fit%22%3A%22contain%22%7D%5D%5D",
            "sku_id": "NK-000006",
            "name": "Hada Collection Kingman Turquoise Necklace",
            "qty": 200,
            "price": "$ 60.50",
            "raw_price": 60.5,
            "currency": "$",
            "amount": "$ 12100.00",
            "raw_amount": 12100.0,
            "hinges_values": "",
            "offered_price": "$ 60.50",
            "raw_offered_price": 60.5,
            "discount": "",
            "note": "",
            "is_custom_product": False,
            "product_attributes": [],
            "applied_modifiers": {},
            "inventory": {
                "inventory_tracking_enabled": True,
                "available_quantity": 999.0,
                "reserved_quantity": 1.0,
                "in_stock_quantity": 1000.0,
                "backorder_allowed": False,
                "backorder_available_quantity": 0,
                "backorder_reserved_quantity": 0.0,
                "on_order_quantity": 100.0,
                "on_order_date": None,
                "total_available": 999.0,
                "total_reserved": 1.0,
                "inventory_status": "IN_STOCK",
                "out_of_stock_threshold": 0.0,
                "created_at": 1700902945.557776,
                "created_at_milliseconds": 1700902945557,
                "updated_at": 1723655346.997567,
                "updated_at_milliseconds": 1723655346997,
                "on_order_details": [
                    {
                        "quantity": 100,
                        "date": None,
                        "identifier": "on_order_0"
                    }
                ],
                "in_transit_details": [
                    {
                        "quantity": 0,
                        "date": None,
                        "identifier": "in_transit_0"
                    }
                ],
                "notes": ""
            },
            "group_number": 0,
            "group_name": "Ungrouped",
            "priority": 13,
            "raw_group_total": 0,
            "group_total": "$ 0"
        },
        {
            "ser_no": "14",
            "image_url": "https://fileserver-g-p.sourcerer.tech/files/96d0ee7a-8126-47e2-bc02-225839e1d30c?quality=20&transforms=%5B%5B%22resize%22%2C%7B%22width%22%3A100%2C%22height%22%3A100%2C%22background%22%3A%22white%22%2C%22fit%22%3A%22contain%22%7D%5D%5D",
            "sku_id": "NK-000723",
            "name": "Hada Collection Kingman Turquoise Necklace",
            "qty": 200,
            "price": "$ 55.00",
            "raw_price": 55.0,
            "currency": "$",
            "amount": "$ 11000.00",
            "raw_amount": 11000.0,
            "hinges_values": "",
            "offered_price": "$ 55.00",
            "raw_offered_price": 55.0,
            "discount": "",
            "note": "",
            "is_custom_product": False,
            "product_attributes": [],
            "applied_modifiers": {},
            "inventory": {
                "inventory_tracking_enabled": True,
                "available_quantity": 1000.0,
                "reserved_quantity": 0.0,
                "in_stock_quantity": 1000.0,
                "backorder_allowed": False,
                "backorder_available_quantity": 0,
                "backorder_reserved_quantity": 0.0,
                "on_order_quantity": 100.0,
                "on_order_date": None,
                "total_available": 1000.0,
                "total_reserved": 0.0,
                "inventory_status": "IN_STOCK",
                "out_of_stock_threshold": 0.0,
                "created_at": 1702507209.903254,
                "created_at_milliseconds": 1702507209903,
                "updated_at": 1720633947.143504,
                "updated_at_milliseconds": 1720633947143,
                "on_order_details": [
                    {
                        "quantity": 100,
                        "date": None,
                        "identifier": "on_order_0"
                    }
                ],
                "in_transit_details": [
                    {
                        "quantity": 0,
                        "date": None,
                        "identifier": "in_transit_0"
                    }
                ],
                "notes": ""
            },
            "group_number": 0,
            "group_name": "Ungrouped",
            "priority": 14,
            "raw_group_total": 0,
            "group_total": "$ 0"
        },
        {
            "ser_no": "15",
            "image_url": "https://fileserver-g-p.sourcerer.tech/files/662b37d8-0141-480c-ab56-ad3ad1411662?quality=20&transforms=%5B%5B%22resize%22%2C%7B%22width%22%3A100%2C%22height%22%3A100%2C%22background%22%3A%22white%22%2C%22fit%22%3A%22contain%22%7D%5D%5D",
            "sku_id": "ER-000044",
            "name": "Hada Collections Kingman Turquoise Earrings",
            "qty": 60,
            "price": "$ 66.00",
            "raw_price": 66.0,
            "currency": "$",
            "amount": "$ 3960.00",
            "raw_amount": 3960.0,
            "hinges_values": "",
            "offered_price": "$ 66.00",
            "raw_offered_price": 66.0,
            "discount": "",
            "note": "",
            "is_custom_product": False,
            "product_attributes": [],
            "applied_modifiers": {},
            "inventory": {
                "inventory_tracking_enabled": True,
                "available_quantity": 1000.0,
                "reserved_quantity": 0.0,
                "in_stock_quantity": 1000.0,
                "backorder_allowed": False,
                "backorder_available_quantity": 0,
                "backorder_reserved_quantity": 0.0,
                "on_order_quantity": 100.0,
                "on_order_date": None,
                "total_available": 1000.0,
                "total_reserved": 0.0,
                "inventory_status": "IN_STOCK",
                "out_of_stock_threshold": 0.0,
                "created_at": 1700902945.557776,
                "created_at_milliseconds": 1700902945557,
                "updated_at": 1716245416.949774,
                "updated_at_milliseconds": 1716245416949,
                "on_order_details": [
                    {
                        "quantity": 100,
                        "date": None,
                        "identifier": "on_order_0"
                    }
                ],
                "in_transit_details": [
                    {
                        "quantity": 0,
                        "date": None,
                        "identifier": "in_transit_0"
                    }
                ],
                "notes": ""
            },
            "group_number": 0,
            "group_name": "Ungrouped",
            "priority": 15,
            "raw_group_total": 0,
            "group_total": "$ 0"
        }
    ],
    "tenant_address": "105 W Historic Hwy 66, Gallup, NM 87301, USA",
    "img_logo": "https://sourcerer.tech/assets/44d56824-b537-478e-8823-622f54376a60",
    "header": "Indian Touch of Gallup",
    "attrs_to_show": [],
    "all_document_data": {
        "id": "ad70c3b4-f122-4f99-b0a8-ed2ecb76b105",
        "system_id": "WC_01005",
        "reference_id": None,
        "source": "sales_rep",
        "offline_system_id": "",
        "type": "order",
        "tenant_id": "7b53408e-c29a-47b8-81c1-8a06c0980cef",
        "created_by": "e5d90d24-05f0-4704-ae63-b333f2717df6",
        "updated_by": "e5d90d24-05f0-4704-ae63-b333f2717df6",
        "owner": "e5d90d24-05f0-4704-ae63-b333f2717df6",
        "buyer_id": "1cfc2740-b3aa-4daa-8548-ef07eaff68ad",
        "expired_at": None,
        "cart_id": "7cce1f34-57e8-416a-a6d1-72d6fd453c5b",
        "orignal_order_id": "a4f994d7-c009-46f6-8f9b-addf5495f635",
        "date": None,
        "document_status": "draft",
        "total_value": 132027.5,
        "payment_due_date": None,
        "payment_transaction_id": None,
        "payment_transaction_details": None,
        "payment_status": "PENDING",
        "attributes": {
            "billing_address": {
                "id": "18becbd0-bd9e-4414-9c35-6fec33fd7f1c",
                "first_name": "",
                "last_name": "",
                "country_code": "",
                "phone": "",
                "email": "",
                "city": "Santa Maria",
                "state": "California",
                "country": "United States of America",
                "pincode": "93455",
                "street_address": "275 W Waller Ln",
                "address_line_2": "",
                "reference_id": "",
                "attribute_values": []
            },
            "shipping_address": {
                "id": "1333fa8e-7285-46c1-96e1-72b010166a49",
                "first_name": "Vintage",
                "last_name": "Boho ",
                "country_code": "",
                "phone": "",
                "email": "",
                "city": "Santa Maria",
                "state": "California",
                "country": "United States of America",
                "pincode": "93455",
                "street_address": "275 W Waller Ln",
                "address_line_2": "",
                "reference_id": "",
                "attribute_values": []
            },
            "payment_method": "",
            "payment_method_id": None,
            "payment_terms": "",
            "freight_terms": "",
            "notification_email_ids": [
                "mich.g.miller@gmail.com"
            ],
            "shipping_method": "",
            "primary_contact": {
                "id": "ac7e6dd8-2d2d-48f9-9f81-4c4ec50d8537",
                "email": "mich.g.miller@gmail.com",
                "phone": "8052606868",
                "country_code": "+1",
                "first_name": "Michelle",
                "last_name": "Miller",
                "designation": "",
                "reference_id": ""
            },
            "shipping_terms": None,
            "vendor_po": None,
            "customer_po": None,
            "carrier_name": None,
            "carrier_service": None,
            "date_scheduled": None,
            "date_issued": None,
            "auto_charges_calculation_enabled": False,
            "customer_consent": False,
            "signature": None,
            "written_for": "04bb7787-5cbb-4139-a609-00d70741a608",
            "written_by": "e5d90d24-05f0-4704-ae63-b333f2717df6",
            "email_history": [],
            "payment_method_v2": {}
        },
        "fulfillment_status": "UNFULFILLED",
        "fulfillment_details": None,
        "total_payment_received": None,
        "refund_details": None,
        "last_synced_with_source_at": None,
        "customer_consent": False,
        "signature": None,
        "entity_source": "wizorder",
        "is_sync": False,
        "last_sync_at": None,
        "last_sync_status": None,
        "last_sync_message": None,
        "created_at": "2024-10-03T19:59:46.222639",
        "updated_at": "2024-10-03T19:59:46.287011",
        "status": "published",
        "child": {},
        "charges": [],
        "total_amount_due": 132027.5,
        "all_payment_received_total": 0,
        "all_payment_refunded_total": 0,
        "excess_payment_received": 0,
        "created_by_name": "Nemo",
        "created_by_email": "nativecityjewelry@gmail.com",
        "created_by_phone": "5059061382",
        "created_by_department": "",
        "updated_by_name": "Nemo",
        "updated_by_email": "nativecityjewelry@gmail.com",
        "updated_by_phone": "5059061382",
        "updated_by_department": "",
        "written_by_name": "Nemo",
        "written_by_email": "nativecityjewelry@gmail.com",
        "written_by_phone": "5059061382",
        "written_by_department": "",
        "written_for_name": "Omar A.",
        "written_for_email": "indiantouchofgallup@msn.com",
        "written_for_phone": "5058706364",
        "written_for_department": "CEO",
        "sales_rep_name": "Nemo",
        "sales_rep_email": "nativecityjewelry@gmail.com",
        "sales_rep_phone": "5059061382",
        "sales_rep_department": "",
        "catalog_name": "Wholesale",
        "claim_form_added": False
    },
    "transactions": {
        "transactions": [],
        "invoices": [],
        "authorized_transactions": [],
        "total_authorized_amount": 0
    },
    "buyer_details": {
        "id": "1cfc2740-b3aa-4daa-8548-ef07eaff68ad",
        "name": "Vintage Boho Bags",
        "reference_id": None,
        "type_of_customer": None,
        "sales_rep": "Omar A.",
        "sales_rep_email": "indiantouchofgallup@msn.com",
        "sales_rep_phone": "5058706364",
        "sales_rep_department": "CEO",
        "buyer_group": None,
        "location": "Santa Maria, usa",
        "contact_person_name": "Michelle Miller",
        "label": {
            "background_color": "",
            "text_color": "",
            "text": ""
        },
        "primary_contact": {
            "email": "mich.g.miller@gmail.com",
            "phone": "8052606868",
            "country_code": "+1"
        },
        "payment_method": {
            "payment_method_type": "card",
            "payment_method_id": "96456d5c-0039-4052-8423-08cb71095914",
            "title": "Ending in 1005",
            "sub_title": "Expiry 07/26",
            "logo": "https://sourcerer.tech/assets/3ad5f693-47a6-44e7-8f38-1546a8034d26",
            "card_type": "american_express",
            "address_1": "275 W Waller Ln",
            "address_2": "",
            "state": "CA",
            "city": "Santa Maria",
            "zip": "93455",
            "country": "USA",
            "card_name": "Vintage boho",
            "is_default": False,
            "is_selected": False,
            "is_usable_in_vt": True,
            "is_tokenized": True,
            "is_authorized": False,
            "authorized_amount": 0
        },
        "wallet_balance": 0.0,
        "analytics": {
            "today": {
                "total_revenue": {
                    "value": "6,200",
                    "percentage": "100%",
                    "orders": 2,
                    "quotes": 5
                },
                "total_orders": {
                    "value": "2",
                    "biggest_order": "4,000"
                },
                "total_quotes": {
                    "value": "5",
                    "biggest_quote": "ABC",
                    "biggest_quote_value": "13,450"
                },
                "total_drafts": {
                    "value": "16",
                    "orders": 10,
                    "quotes": 6
                }
            },
            "last_week": {},
            "last_30_days": {},
            "last_6_months": {},
            "last_12_months": {},
            "all_time": {}
        },
        "recent_orders": [
            {
                "date": "12 Aug 2023",
                "type": "sent",
                "id": 123456789,
                "items": 12,
                "price": "4,000",
                "label": {
                    "background_color": "",
                    "text_color": "",
                    "text": ""
                }
            },
            {
                "date": "12 Aug 2023",
                "type": "sent",
                "id": 123456789,
                "items": 12,
                "price": "2,200"
            }
        ]
    },
    "buyer_attributes": [
        {
            "id": "e6a4324d-9fe0-4507-ba4a-e8142a67332e",
            "name": "Tax ID",
            "type": "text",
            "value": "",
            "priority": 0,
            "required": False,
            "is_display": True,
            "options": [],
            "updated_at": "2023-11-25T14:26:30.903530",
            "created_at": "2023-11-25T14:26:30.903530",
            "is_display_exclusion_type": [],
            "required_exclusion_type": [],
            "validations": {},
            "is_label_display": False
        }
    ],
    "contact_attributes": {},
    "address_attributes": {},
    "signature": "",
    "document_status": "draft",
    "document_created_by_name": "Nemo",
    "document_created_by_email": "nativecityjewelry@gmail.com",
    "document_created_by_phone": "5059061382",
    "document_created_by_department": "",
    "document_updated_by_name": "Nemo",
    "document_updated_by_email": "nativecityjewelry@gmail.com",
    "document_updated_by_phone": "5059061382",
    "document_updated_by_department": "",
    "document_sales_rep": "Nemo",
    "document_sales_rep_email": "nativecityjewelry@gmail.com",
    "document_sales_rep_phone": "5059061382",
    "document_sales_rep_department": "",
    "po_number": ""
}